namespace offsets
{
	namespace AItem
	{
			constexpr auto DebugTextChanged = 0x2c0; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto PickedUpState = 0x2d0; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnStaticMeshChanged = 0x2e0; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnSkeletalMeshChanged = 0x2f0; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto Mesh = 0x310; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto ThrowingComponent = 0x428; // Size: 8, Type: struct UThrowingComponent*
			constexpr auto _caption = 0x430; // Size: 24, Type: struct FText
			constexpr auto _description = 0x448; // Size: 24, Type: struct FText
			constexpr auto _uses = 0x460; // Size: 4, Type: int32_t
			constexpr auto _health = 0x464; // Size: 4, Type: float
			constexpr auto _maxHealth = 0x468; // Size: 4, Type: float
			constexpr auto _maxHealthPercentageAfterReachingBadQuality = 0x46c; // Size: 4, Type: float
			constexpr auto _weight = 0x470; // Size: 4, Type: float
			constexpr auto _initialWeightUsed = 0x474; // Size: 4, Type: float
			constexpr auto _maxWaterWeightAsRatioOfWeight = 0x478; // Size: 4, Type: float
			constexpr auto _radiationDecreaseRate = 0x47c; // Size: 4, Type: float
			constexpr auto _maxRadiationAmountPerWeight = 0x480; // Size: 4, Type: float
			constexpr auto _baseRadiationPropagationFactor = 0x484; // Size: 4, Type: float
			constexpr auto _canEverDecontaminate = 0x488; // Size: 1, Type: bool
			constexpr auto _choppingRecipeDataAsset = 0x490; // Size: 8, Type: struct UChoppingRecipeDataAsset*
			constexpr auto _shouldBeMaintained = 0x498; // Size: 1, Type: bool
			constexpr auto _canBeDropped = 0x499; // Size: 1, Type: bool
			constexpr auto _canTakeInHands = 0x49a; // Size: 1, Type: bool
			constexpr auto _canBeVisibleInVicinity = 0x49b; // Size: 1, Type: bool
			constexpr auto _canPlaceItemsOn = 0x49c; // Size: 1, Type: bool
			constexpr auto _canPlaceBlueprintsOn = 0x49d; // Size: 1, Type: bool
			constexpr auto _overrideSkeletalMesh = 0x4a0; // Size: 8, Type: struct USkeletalMesh*
			constexpr auto _overrideSkeletalMeshRelativeTransform = 0x4b0; // Size: 48, Type: struct FTransform
			constexpr auto _ifExhausted = 0x4e0; // Size: 1, Type: uint8_t 
			constexpr auto _resourceAmountUsedPerWash = 0x4e4; // Size: 4, Type: float
			constexpr auto _inventoryIcon = 0x4e8; // Size: 8, Type: struct UTexture2D*
			constexpr auto _inventoryIconInHands = 0x4f0; // Size: 8, Type: struct UTexture2D*
			constexpr auto _outsideInventoryIcon = 0x4f8; // Size: 8, Type: struct UTexture2D*
			constexpr auto _sizeX = 0x500; // Size: 4, Type: uint32_t
			constexpr auto _sizeY = 0x504; // Size: 4, Type: uint32_t
			constexpr auto _inventoryWhiteList = 0x508; // Size: 16, Type: struct TArray<struct UBaseItemTag*>
			constexpr auto _inventoryBlackList = 0x518; // Size: 16, Type: struct TArray<struct UBaseItemTag*>
			constexpr auto _maxContainedWeight = 0x528; // Size: 4, Type: float
			constexpr auto _canContainNonEmptyItems = 0x52c; // Size: 1, Type: bool
			constexpr auto _canBeContainedIfNonEmpty = 0x52d; // Size: 1, Type: bool
			constexpr auto _isIgnoredBySpawners = 0x52e; // Size: 1, Type: bool
			constexpr auto _spawnTimeoutPerPlayer = 0x530; // Size: 8, Type: struct FFloatInterval
			constexpr auto _itemLocation = 0x538; // Size: 15, Type: struct FItemLocation
			constexpr auto _rarity = 0x547; // Size: 1, Type: uint8_t 
			constexpr auto _itemSpawnTypes = 0x548; // Size: 32, Type: struct FGameplayTagContainer
			constexpr auto _itemSpawnGroup = 0x568; // Size: 8, Type: struct FGameplayTag
			constexpr auto _spawnLocationOffset = 0x570; // Size: 12, Type: struct FVector
			constexpr auto _spawnRotationOffset = 0x57c; // Size: 12, Type: struct FRotator
			constexpr auto _spawnRotationRandomization = 0x588; // Size: 4, Type: float
			constexpr auto _placementCollisionUpOffset = 0x58c; // Size: 4, Type: float
			constexpr auto _shouldOverrideUsageWhenSpawnedBySpawners = 0x590; // Size: 1, Type: bool
			constexpr auto _initialUsageWhenSpawnedBySpawners = 0x594; // Size: 4, Type: float
			constexpr auto _randomizeUsageWhenSpawnedBySpawners = 0x598; // Size: 4, Type: float
			constexpr auto _itemTags = 0x5a0; // Size: 16, Type: struct TArray<struct UBaseItemTag*>
			constexpr auto _ownedItemTags = 0x5b0; // Size: 16, Type: struct TArray<struct UBaseItemTag*>
			constexpr auto _noiseLevel = 0x5c0; // Size: 1, Type: uint8_t 
			constexpr auto _motionNoise = 0x5c8; // Size: 8, Type: struct FItemMotionNoise
			constexpr auto _inventoryHandlingSound = 0x5d0; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _destroyedSound = 0x5d8; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _craftingIngredientTypes = 0x5e0; // Size: 16, Type: struct TArray<UCraftingIngredientType*>
			constexpr auto _craftingInteraction = 0x5f0; // Size: 1, Type: uint8_t 
			constexpr auto _defaultCraftingParts = 0x5f8; // Size: 16, Type: struct TArray<struct FCraftingPart>
			constexpr auto _damageOnUse = 0x608; // Size: 4, Type: float
			constexpr auto _damageOverTime = 0x60c; // Size: 4, Type: float
			constexpr auto _autoDestructTime = 0x610; // Size: 4, Type: float
			constexpr auto _allowContainedItemsDecay = 0x614; // Size: 1, Type: bool
			constexpr auto _shouldDestroyContainedItemsOnDestroyEvent = 0x61c; // Size: 1, Type: bool
			constexpr auto _minTemperatureForHeatDamage = 0x620; // Size: 4, Type: float
			constexpr auto _containedDamageStartPercentage = 0x624; // Size: 4, Type: float
			constexpr auto _damageResponseFactor = 0x628; // Size: 4, Type: float
			constexpr auto _attachmentSocketMountType = 0x630; // Size: 8, Type: UAttachmentSocketMountType*
			constexpr auto _attachmentSockets = 0x638; // Size: 16, Type: struct TArray<struct FAttachmentSocket>
			constexpr auto _holsterAttachmentSocketMountType = 0x648; // Size: 8, Type: UAttachmentSocketMountType*
			constexpr auto _attachmentSocketsOffset = 0x650; // Size: 80, Type: struct TMap<UAttachmentSocketMountType*, struct FAttachmentSocketOffset>
			constexpr auto _enableGlowOnBeginPlay = 0x6a0; // Size: 1, Type: bool
			constexpr auto _enableAwarenessGlow = 0x6a1; // Size: 1, Type: bool
			constexpr auto _enableHoverGlow = 0x6a2; // Size: 1, Type: bool
			constexpr auto _placementMeshOverride = 0x6a8; // Size: 8, Type: struct UStaticMesh*
			constexpr auto _staticMeshHolsterOverride = 0x6b0; // Size: 8, Type: struct UStaticMesh*
			constexpr auto _skeletalMeshHolsterOverride = 0x6b8; // Size: 8, Type: struct USkeletalMesh*
			constexpr auto _hasHighLoadPriorityInVirtualization = 0x6c0; // Size: 1, Type: bool
			constexpr auto _virtualizationDistanceOffset = 0x6c4; // Size: 4, Type: float
			constexpr auto _canEverBeVirtualized = 0x6c8; // Size: 1, Type: bool
			constexpr auto _isSubjectToAllowMinesConfig = 0x6ca; // Size: 1, Type: bool
			constexpr auto _resultHealthMultiplierWhenCraftingIngredient = 0x6cc; // Size: 4, Type: float
			constexpr auto _preferredDamagePerUpdate = 0x6d0; // Size: 4, Type: float
			constexpr auto _useHandCorrections = 0x6d4; // Size: 1, Type: bool
			constexpr auto _vicinityCheckDistance = 0x6d8; // Size: 4, Type: float
			constexpr auto _reachabilityTestZOffset = 0x6dc; // Size: 4, Type: float
			constexpr auto _stackableClasses = 0x6e0; // Size: 16, Type: struct TArray<UObject*>
			constexpr auto _maxNumOfStacks = 0x6f0; // Size: 4, Type: int32_t
			constexpr auto _bloodDryingSpeed = 0x6f4; // Size: 4, Type: float
			constexpr auto _stackData = 0x6f8; // Size: 16, Type: struct FItemStackData
			constexpr auto _craftingPartsData = 0x710; // Size: 16, Type: struct TArray<struct UItemStateBase*>
			constexpr auto _skeletalMeshComponent = 0x728; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto _weightUsed = 0x734; // Size: 4, Type: float
			constexpr auto _repServerEntitySetupAndId = 0x750; // Size: 8, Type: struct FPackedEntitySetupAndId
			constexpr auto _itemComponents = 0x758; // Size: 16, Type: struct TArray<struct UItemComponent*>
			constexpr auto _attachParentObject = 0x768; // Size: 8, Type: struct AActor*
			constexpr auto _visibilityReplication = 0x770; // Size: 8, Type: struct FVisibilityReplication
			constexpr auto _radiationAmount = 0x7b4; // Size: 4, Type: float
			constexpr auto _uncraftTime = 0x7b8; // Size: 4, Type: float
			constexpr auto _replicatedState = 0x7c0; // Size: 8, Type: uint64_t
			constexpr auto _flagsReplicated = 0x7c9; // Size: 1, Type: char
			constexpr auto _tempSceneComponent = 0x7f0; // Size: 8, Type: struct USceneComponent*
			constexpr auto _expirationTime = 0x800; // Size: 8, Type: int64_t
			constexpr auto _stacks = 0x808; // Size: 16, Type: struct TArray<struct FInventoryStackData>
			constexpr auto _stackExhaustedSuccessorItem = 0x818; // Size: 8, Type: struct AItem*
			constexpr auto _parentContainer = 0x820; // Size: 16, Type: struct TScriptInterface<IInventoryContainer>
			constexpr auto _parentInventoryNode = 0x830; // Size: 16, Type: struct TScriptInterface<IInventoryNode>
			constexpr auto _craftingParts = 0x8c0; // Size: 16, Type: struct TArray<struct FCraftingPart>
	}
} 
