namespace offsets
{
	namespace APrisoner
	{
			constexpr auto SkillComponent = 0x7e0; // Size: 8, Type: struct UPrisonerSkillComponent*
			constexpr auto InventoryComponent = 0x7e8; // Size: 8, Type: struct UPrisonerInventoryComponent*
			constexpr auto AppearanceComponent = 0x7f0; // Size: 8, Type: struct UPrisonerAppearanceComponent*
			constexpr auto MeleeCombatComponent = 0x7f8; // Size: 8, Type: struct UMeleeCombatComponent*
			constexpr auto HitReactComponent = 0x800; // Size: 8, Type: struct UHitReactComponent*
			constexpr auto PhysicalAnimationComponent = 0x808; // Size: 8, Type: struct UPhysicalAnimationComponent*
			constexpr auto InteractionComponent = 0x810; // Size: 8, Type: struct UInteractionComponent*
			constexpr auto SensingComponent = 0x818; // Size: 8, Type: struct UPawnSensingComponent*
			constexpr auto BaseInteractionComponent = 0x820; // Size: 8, Type: struct UBaseInteractionComponent*
			constexpr auto IgnoreMovementSettings = 0x828; // Size: 1, Type: bool
			constexpr auto OverrideAimOffset = 0x829; // Size: 1, Type: bool
			constexpr auto AimOffsetOverride = 0x82c; // Size: 12, Type: struct FRotator
			constexpr auto EyesLookAtTargetOverride = 0x838; // Size: 8, Type: struct AActor*
			constexpr auto IsFriendly = 0x840; // Size: 1, Type: bool
			constexpr auto CanEverBeKnockedOutByMeleeAttack = 0x841; // Size: 1, Type: bool
			constexpr auto ShouldOverrideCharacterTemplate = 0x842; // Size: 1, Type: bool
			constexpr auto CharacterTemplateOverride = 0x848; // Size: 224, Type: struct FCharacterTemplate
			constexpr auto LeftHandAttachmentSocket = 0x928; // Size: 16, Type: struct FAttachmentSocket
			constexpr auto RightHandAttachmentSocket = 0x938; // Size: 16, Type: struct FAttachmentSocket
			constexpr auto LeftShoulderHolsterSocket = 0x948; // Size: 16, Type: struct FAttachmentSocket
			constexpr auto RightShoulderHolsterSocket = 0x958; // Size: 16, Type: struct FAttachmentSocket
			constexpr auto TabModeOpened = 0xae8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto TabModeClosed = 0xaf8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto PanelsClosed = 0xb08; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto HoveredActorChanged = 0xb18; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto RespawnOnKill = 0xb50; // Size: 1, Type: bool
			constexpr auto IKOffsetLeftFoot = 0xb54; // Size: 4, Type: float
			constexpr auto IKOffsetRightFoot = 0xb58; // Size: 4, Type: float
			constexpr auto BorderCrossingPenalty = 0xb5c; // Size: 1, Type: uint8_t 
			constexpr auto BorderCrossingPenaltyChange = 0xb60; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto _bodySimulationComponent = 0xd50; // Size: 8, Type: struct UPrisonerBodySimulationComponent*
			constexpr auto _skinThermalSensingComponent = 0xd58; // Size: 8, Type: struct UThermalSensorComponent*
			constexpr auto _prisonerMeshManager = 0xd60; // Size: 8, Type: struct UPrisonerMeshManager*
			constexpr auto _userProfile = 0xd68; // Size: 8, Type: struct UUserProfile*
			constexpr auto _userId = 0xd70; // Size: 16, Type: struct FString
			constexpr auto _serverUserProfileId = 0xd80; // Size: 8, Type: struct FDbIntegerId
			constexpr auto _userProfileName = 0xd88; // Size: 16, Type: struct FString
			constexpr auto _userFakeName = 0xd98; // Size: 16, Type: struct FString
			constexpr auto _waterParticlesComponentWhenIdle = 0xe10; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto _waterParticlesComponentWhenMoving = 0xe18; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto _waterParticlesComponentWhenDiving = 0xe20; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto _desiredStance = 0xe2e; // Size: 1, Type: uint8_t 
			constexpr auto _targetCrouchStage = 0xe3c; // Size: 4, Type: float
			constexpr auto _desiredPace = 0xe40; // Size: 1, Type: uint8_t 
			constexpr auto _freeLookEnabled = 0xe43; // Size: 1, Type: bool
			constexpr auto _postFreeLookControllerRotationBlendActive = 0xe6c; // Size: 1, Type: bool
			constexpr auto _repAimOffset = 0xe7c; // Size: 12, Type: struct FRotator
			constexpr auto _lastCorpse = 0xec8; // Size: 8, Type: struct APrisonerCorpse*
			constexpr auto _lastEventCorpse = 0xed0; // Size: 8, Type: struct APrisonerCorpse*
			constexpr auto _targetLeanAmount = 0xf0c; // Size: 4, Type: float
			constexpr auto _meleeTarget = 0x16c8; // Size: 8, Type: struct AActor*
			constexpr auto _activeMeleeSkill = 0x16d8; // Size: 8, Type: struct UMeleeSkill*
			constexpr auto _rotationTarget = 0x16f0; // Size: 8, Type: struct AActor*
			constexpr auto _unarmedCombatInputRedirector = 0x16f8; // Size: 8, Type: struct UUnarmedCombatInputRedirector*
			constexpr auto _skillEventHandler = 0x1700; // Size: 8, Type: struct USkillEventHandler*
			constexpr auto _itemInHands = 0x1718; // Size: 8, Type: struct AItem*
			constexpr auto _scopingWithItemInHandsState = 0x1745; // Size: 1, Type: uint8_t 
			constexpr auto _weaponAimingType = 0x1770; // Size: 1, Type: uint8_t 
			constexpr auto _itemInHandsVisualObstructionDepthRep = 0x1794; // Size: 1, Type: char
			constexpr auto _isInCombatMode = 0x18a0; // Size: 1, Type: bool
			constexpr auto _leftShoulderHolsteredItemReplicated = 0x18f8; // Size: 8, Type: struct AItem*
			constexpr auto _rightShoulderHolsteredItemReplicated = 0x1908; // Size: 8, Type: struct AItem*
			constexpr auto _interactDefaultContextMenuTimerHandle = 0x1958; // Size: 8, Type: struct FTimerHandle
			constexpr auto _examinedBy = 0x1960; // Size: 16, Type: struct TArray<struct APrisoner*>
			constexpr auto _tacticsBlobMaterial = 0x1970; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _bodyPartEffects = 0x1978; // Size: 16, Type: struct TArray<struct UParticleSystemComponent*>
			constexpr auto _handsBondage = 0x1988; // Size: 8, Type: struct UBondageComponent*
			constexpr auto _prisonWalletComponent = 0x1990; // Size: 8, Type: struct UPrisonerPrisonWalletComponent*
			constexpr auto _fishingComponent = 0x1998; // Size: 8, Type: struct UPrisonerFishingComponent*
			constexpr auto _musicPlayerComponent = 0x19a0; // Size: 8, Type: struct UPrisonerMusicPlayerComponent*
			constexpr auto _tradingComponent = 0x19a8; // Size: 8, Type: struct UPrisonerTradingComponent*
			constexpr auto _throwingComponent = 0x19b0; // Size: 8, Type: struct UPrisonerThrowComponent*
			constexpr auto _itemDragComponent = 0x19b8; // Size: 8, Type: struct UCharacterItemDragComponent*
			constexpr auto _packedWaterWeight = 0x19dc; // Size: 4, Type: uint32_t
			constexpr auto _gameEvent = 0x1a08; // Size: 8, Type: struct AGameEventBase*
			constexpr auto _gameEventLoadout = 0x1a10; // Size: 8, Type: struct UPrisonerLoadout*
			constexpr auto _nearbyFoliageInfo = 0x1a28; // Size: 16, Type: struct FPrisonerNearbyFoliageInfo
			constexpr auto _collidingNearbyFoliageInfo = 0x1a38; // Size: 16, Type: struct FPrisonerNearbyFoliageInfo
			constexpr auto _nameWidgetComponent = 0x1b10; // Size: 8, Type: struct UWidgetComponent*
			constexpr auto SaveSpawnLocationTag = 0x1b18; // Size: 8, Type: struct UBaseItemTag*
			constexpr auto _deluxeVersion = 0x1b48; // Size: 5, Type: struct FDeluxeVersion
			constexpr auto _examinedPrisoner = 0x1b54; // Size: 8, Type: struct TWeakObjectPtr<APrisoner>
			constexpr auto _killClaimed = 0x1b5c; // Size: 1, Type: bool
			constexpr auto _playingInstrumentState = 0x1b78; // Size: 1, Type: uint8_t 
			constexpr auto _carryingItemState = 0x1b7a; // Size: 1, Type: uint8_t 
			constexpr auto _shouldShowGenitalsOverride = 0x1bb0; // Size: 1, Type: bool
			constexpr auto _repMount = 0x1be0; // Size: 16, Type: struct FPrisonerMountReplication
			constexpr auto _midiDeviceController = 0x1bf0; // Size: 8, Type: struct UMIDIDeviceController*
			constexpr auto _hasInfiniteAmmo = 0x1c38; // Size: 1, Type: bool
			constexpr auto _isInGodMode = 0x1c39; // Size: 1, Type: bool
			constexpr auto _isImmortal = 0x1c3a; // Size: 1, Type: bool
			constexpr auto _isSuperJumpEnabled = 0x1c3b; // Size: 1, Type: bool
			constexpr auto _enablePerComponentReplicationFrequency = 0x1c60; // Size: 1, Type: bool
			constexpr auto _componentsReplicationFrequency[5] = 0x1c64; // Size: 20, Type: float
			constexpr auto _navigationInvokerComponent = 0x1cd8; // Size: 8, Type: struct UNavigationInvokerComponent*
			constexpr auto LegsInjuryTag = 0x1d6c; // Size: 8, Type: struct FGameplayTag
			constexpr auto _vehicleWeaponAimingStance = 0x1df8; // Size: 1, Type: uint8_t 
			constexpr auto _vehicleAimingYawReplicated = 0x1e24; // Size: 4, Type: float
			constexpr auto _activeParachute = 0x1eb0; // Size: 8, Type: struct TWeakObjectPtr<AClothesItem>
			constexpr auto _replicatedBooleans = 0x1ec4; // Size: 1, Type: char
			constexpr auto _commonData = 0x1ed8; // Size: 8, Type: struct UPrisonerCommonData*
			constexpr auto _meshForcedLodIfNotPlayerControlled = 0x1ee0; // Size: 4, Type: int32_t
	}
} 
