namespace offsets
{
	namespace ASentry2
	{
			constexpr auto _pelvisBoneName = 0x7f0; // Size: 8, Type: struct FName
			constexpr auto _eyesViewPointSocketName = 0x7f8; // Size: 8, Type: struct FName
			constexpr auto _longRangeWeaponSocketName = 0x800; // Size: 8, Type: struct FName
			constexpr auto _longRangeWeaponMuzzleFlashBoneNames = 0x808; // Size: 16, Type: struct TArray<struct FName>
			constexpr auto _longRangeWeaponBoneName = 0x818; // Size: 8, Type: struct FName
			constexpr auto _highPrecisionWeaponSocketName = 0x820; // Size: 8, Type: struct FName
			constexpr auto _highPrecisionWeaponBoneName = 0x828; // Size: 8, Type: struct FName
			constexpr auto _grenadeLauncherSocketNames = 0x830; // Size: 16, Type: struct TArray<struct FName>
			constexpr auto _highPrecisionWeaponChargingSocket = 0x840; // Size: 8, Type: struct FName
			constexpr auto _meleeAttackFailureGrenadeDropSocket = 0x848; // Size: 8, Type: struct FName
			constexpr auto _sensorHeightOffset = 0x850; // Size: 4, Type: float
			constexpr auto _damageParticlesSockets = 0x858; // Size: 16, Type: struct TArray<struct FName>
			constexpr auto _fireBulletAudioEvent = 0x868; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _startHighFireRateAttack = 0x870; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _endHighFireRateAttack = 0x878; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _reloadAudioEvent = 0x880; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _highPrecisionWeaponFireShotAudioEvent = 0x888; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _grenadeLaunchAudioEffect = 0x890; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _tearGasGrenadeLaunchAudioEffect = 0x898; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _stunGrenadeLaunchAudioEffect = 0x8a0; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _deathAudioEvent = 0x8a8; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _freezeWarningAudioEvent = 0x8b0; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _dropWeaponsRaiseHandsAudioEvent = 0x8b8; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _walkAwayAudioEvent = 0x8c0; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _beginCombatAudioEvent = 0x8c8; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _startSearchCorpseAudioEvent = 0x8d0; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _stopSearchCorpseAudioEvent = 0x8d8; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _upperBodyRotationAudioEvent = 0x8e0; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _normalAttackMontage = 0x8e8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto _reloadMontageLongRangeWeapon = 0x8f0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto _deathMontage = 0x8f8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto _meleeMontageDescriptions = 0x900; // Size: 16, Type: struct TArray<struct FSentryMeleeAttackDescription>
			constexpr auto _highprecisionAttackMontage = 0x910; // Size: 8, Type: struct UAnimMontage*
			constexpr auto _enemySpottedMontage = 0x918; // Size: 8, Type: struct UAnimMontage*
			constexpr auto _hasUpperBodyRotation = 0x920; // Size: 1, Type: bool
			constexpr auto _upperBodyRotationMaxYawDegrees = 0x924; // Size: 4, Type: float
			constexpr auto _upperBodyRotationHighPrecisionAttackMaxYawDegrees = 0x928; // Size: 4, Type: float
			constexpr auto _upperBodyRotationFactor = 0x92c; // Size: 4, Type: float
			constexpr auto _upperBodyNetSmoothUpdateRotationTime = 0x930; // Size: 4, Type: float
			constexpr auto _upperBodyRotationAngularVelocitySoundThreshold = 0x934; // Size: 4, Type: float
			constexpr auto _upperBodyFocusLocation = 0x93c; // Size: 12, Type: struct FVector
			constexpr auto _hasHighFireRateAttackAnimation = 0x951; // Size: 1, Type: bool
			constexpr auto _gunsLerpFactor = 0x954; // Size: 4, Type: float
			constexpr auto _projectileClass = 0x958; // Size: 8, Type: AProjectile*
			constexpr auto _maxLongRangeWeaponHalfAngle = 0x960; // Size: 4, Type: float
			constexpr auto _highPrecisonWeaponProjectileClass = 0x970; // Size: 8, Type: AProjectile*
			constexpr auto _maxHighPrecisionWeaponHalfAngle = 0x978; // Size: 4, Type: float
			constexpr auto _grenadeProjectileClass = 0x988; // Size: 8, Type: AProjectile*
			constexpr auto _tearGasGrenadeItemClass = 0x990; // Size: 8, Type: AItem*
			constexpr auto _stunGrenadeItemClass = 0x998; // Size: 8, Type: AItem*
			constexpr auto _meleeAttackFailureGrenadeItemClass = 0x9a0; // Size: 8, Type: AItem*
			constexpr auto _stunGreandeExplosionDelayAfterReachingGround = 0x9a8; // Size: 4, Type: float
			constexpr auto _itemGreandeDirectionRandomizationAngle = 0x9ac; // Size: 4, Type: float
			constexpr auto _sentryMovementComponent = 0x9b8; // Size: 8, Type: struct USentryMovementComponent*
			constexpr auto _hitReactComponent = 0x9c0; // Size: 8, Type: struct UHitReactComponent*
			constexpr auto _hitReactTag = 0x9c8; // Size: 8, Type: struct FGameplayTag
			constexpr auto _isAlive = 0x9d0; // Size: 1, Type: bool
			constexpr auto _maxHealth = 0x9d4; // Size: 4, Type: float
			constexpr auto _healthStateThresholds[6] = 0x9e0; // Size: 24, Type: float
			constexpr auto _armorDamageReductionExplosion = 0x9f8; // Size: 4, Type: float
			constexpr auto _armorDamageReductionCollision = 0x9fc; // Size: 4, Type: float
			constexpr auto _exlosionDamageHitReactThreshold = 0xa00; // Size: 4, Type: float
			constexpr auto _isStunnedDuringHitReact = 0xa04; // Size: 1, Type: bool
			constexpr auto _longRangeWeaponFireRate = 0xa08; // Size: 4, Type: float
			constexpr auto _longRangeWeaponFireRateVariation = 0xa0c; // Size: 4, Type: float
			constexpr auto _longRangeWeaponHalfAngleDegrees = 0xa10; // Size: 4, Type: float
			constexpr auto _maxAmmunitionLongRangeWeapon = 0xa14; // Size: 4, Type: int32_t
			constexpr auto _maxAmmunitionMediumRangeWeapon = 0xa1c; // Size: 4, Type: int32_t
			constexpr auto _longRangeWeaponSpreadHalfAngle = 0xa24; // Size: 4, Type: float
			constexpr auto _mediumRangeWeaponFireRate = 0xa28; // Size: 4, Type: float
			constexpr auto _mediumRangeWeaponHalfAngleDegrees = 0xa2c; // Size: 4, Type: float
			constexpr auto _mediumRangeWeaponActivationDistance = 0xa30; // Size: 4, Type: float
			constexpr auto _meleeAttackRate = 0xa34; // Size: 4, Type: float
			constexpr auto _meleeAttackActivationDistance = 0xa38; // Size: 4, Type: float
			constexpr auto _weaponOverrideAimLocationRep = 0xa44; // Size: 12, Type: struct FVector
			constexpr auto _patrolPoints = 0xa78; // Size: 16, Type: struct TArray<struct FSentryPatrolPoint>
			constexpr auto _muzzlePS = 0xa88; // Size: 8, Type: struct UParticleSystem*
			constexpr auto _muzzlePSCs = 0xa90; // Size: 16, Type: struct TArray<struct UParticleSystemComponent*>
			constexpr auto _highPrecisionWeaponMuzzlePS = 0xaa0; // Size: 8, Type: struct UParticleSystem*
			constexpr auto _highPrecisionWeaponMuzzlePSC = 0xaa8; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto _muzzleEffectsScaleDistanceStart = 0xab0; // Size: 4, Type: float
			constexpr auto _muzzleEffectsScaleDistanceRange = 0xab4; // Size: 4, Type: float
			constexpr auto _muzzleEffectsScaleByDistanceFactor = 0xab8; // Size: 4, Type: float
			constexpr auto _highPrecisionWeaponChargingPS = 0xac0; // Size: 8, Type: struct UNiagaraSystem*
			constexpr auto _highPrecisionWeaponChargingPSC = 0xac8; // Size: 8, Type: struct UNiagaraComponent*
			constexpr auto _lightMaterialSlotName = 0xb08; // Size: 8, Type: struct FName
			constexpr auto _additionalLightsMaterialSlotNames = 0xb10; // Size: 16, Type: struct TArray<struct FName>
			constexpr auto _normalLightColor = 0xb20; // Size: 4, Type: struct FColor
			constexpr auto _alertedLightColor = 0xb24; // Size: 4, Type: struct FColor
			constexpr auto _combatLightColor = 0xb28; // Size: 4, Type: struct FColor
			constexpr auto _emissionColorParameterName = 0xb30; // Size: 8, Type: struct FName
			constexpr auto _spottingPercentage = 0xb38; // Size: 4, Type: float
			constexpr auto _damageEffectsNumPerHealthStateData[6] = 0xb3c; // Size: 96, Type: struct FInt32Range
			constexpr auto _damageParticleEffectsPSData = 0xba0; // Size: 16, Type: struct TArray<struct FSentryDamageEffectData>
			constexpr auto _damageParticleIntensityPerHealthState[6] = 0xc00; // Size: 24, Type: float
			constexpr auto _stompShakeEffectRadius = 0xc18; // Size: 4, Type: float
			constexpr auto _stompShakeMaxEffectRadius = 0xc1c; // Size: 4, Type: float
			constexpr auto _stompShakeEffectFalloffExponent = 0xc20; // Size: 4, Type: float
			constexpr auto _stompCameraShake = 0xc28; // Size: 8, Type: UMatineeCameraShake*
			constexpr auto _laserMeshComponent = 0xc30; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto _canEverDrawLaser = 0xc38; // Size: 1, Type: bool
			constexpr auto _walkSpeedMultiplier = 0xc3c; // Size: 4, Type: float
			constexpr auto _walkSpeedMultiplierMin = 0xc40; // Size: 4, Type: float
			constexpr auto _walkSpeedMultiplierMax = 0xc44; // Size: 4, Type: float
			constexpr auto _corpseSearchDuration = 0xc4c; // Size: 4, Type: float
			constexpr auto _packedGeneralData = 0xc51; // Size: 1, Type: char
			constexpr auto _packedCombatData = 0xc52; // Size: 2, Type: uint16_t
			constexpr auto _autoSaveInterval = 0xc60; // Size: 4, Type: float
			constexpr auto _shouldSaveAndLoadSentry = 0xc68; // Size: 1, Type: bool
			constexpr auto _foe = 0xc88; // Size: 8, Type: struct TWeakObjectPtr<APawn>
	}
} 
