namespace offsets
{
	namespace AWeatherController2
	{
			constexpr auto _maxHeightAboveSeaLevel = 0x268; // Size: 4, Type: float
			constexpr auto _sun = 0x270; // Size: 8, Type: struct UDirectionalLightComponent*
			constexpr auto _timeOfDay = 0x278; // Size: 4, Type: float
			constexpr auto _canStartTimeOfDayBeOverridenByConfig = 0x27c; // Size: 1, Type: bool
			constexpr auto _timeOfDaySpeed = 0x280; // Size: 4, Type: float
			constexpr auto _canTimeOfDaySpeedBeOverridenByConfig = 0x284; // Size: 1, Type: bool
			constexpr auto _sunIntensity = 0x288; // Size: 4, Type: float
			constexpr auto _sunFullEclipseMult = 0x28c; // Size: 4, Type: float
			constexpr auto _sunAzimuthDegrees = 0x290; // Size: 4, Type: float
			constexpr auto _sunriseTime = 0x294; // Size: 4, Type: float
			constexpr auto _canSunriseTimeBeOverridenByConfig = 0x298; // Size: 1, Type: bool
			constexpr auto _sunsetTime = 0x29c; // Size: 4, Type: float
			constexpr auto _canSunsetTimeBeOverridenByConfig = 0x2a0; // Size: 1, Type: bool
			constexpr auto _dawnDuskTresholdAngle = 0x2a4; // Size: 4, Type: float
			constexpr auto _maxSolarIrradiance = 0x2ac; // Size: 4, Type: float
			constexpr auto _moon = 0x2b0; // Size: 8, Type: struct UDirectionalLightComponent*
			constexpr auto _moonRotation = 0x2b8; // Size: 4, Type: float
			constexpr auto _moonIntensityMult = 0x2bc; // Size: 4, Type: float
			constexpr auto _moonLightTint = 0x2c0; // Size: 16, Type: struct FLinearColor
			constexpr auto _moonStarsMaterial = 0x2d0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto _moonStarsMaterialDynamic = 0x2d8; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _starsSphere = 0x2e0; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto _starsSphereDistance = 0x2e8; // Size: 4, Type: float
			constexpr auto _starsSphereRotation = 0x2ec; // Size: 12, Type: struct FRotator
			constexpr auto _nightLight = 0x2f8; // Size: 8, Type: struct UDirectionalLightComponent*
			constexpr auto _nightLightIntensity = 0x300; // Size: 4, Type: float
			constexpr auto _nightLightIntensityRange = 0x304; // Size: 8, Type: struct FFloatInterval
			constexpr auto _nightLightColor = 0x30c; // Size: 16, Type: struct FLinearColor
			constexpr auto _skyAmbientReflEnv = 0x320; // Size: 8, Type: struct USkyLightComponent*
			constexpr auto _skyAtmosphere = 0x328; // Size: 8, Type: struct USkyAtmosphereComponent*
			constexpr auto _skyAmbientIntensity = 0x330; // Size: 4, Type: float
			constexpr auto _skyAmbientOcclusionTint = 0x338; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _volumetricClouds = 0x3c0; // Size: 8, Type: struct UVolumetricCloudComponent*
			constexpr auto _volumetricCloudsMaterialLQ = 0x3c8; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto _volumetricCloudsMaterialHQ = 0x3d0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto _volumetricCloudsMaterialDynamic = 0x3d8; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _cirrostratusCoverage = 0x3e0; // Size: 4, Type: float
			constexpr auto _cirrostratusSunlightThroughput = 0x3e4; // Size: 4, Type: float
			constexpr auto _cirrostratusCoverageMaterialParamRemap = 0x3e8; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _cumulonimbusCoverage = 0x470; // Size: 4, Type: float
			constexpr auto _cumulonimbusSunlightThroughput = 0x474; // Size: 4, Type: float
			constexpr auto _cumulonimbusCoverageMaterialParamRemap = 0x478; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _nimbostratusCoverage = 0x500; // Size: 4, Type: float
			constexpr auto _nimbostratusSunlightThroughput = 0x504; // Size: 4, Type: float
			constexpr auto _nimbostratusCoverageMaterialParamRemap = 0x508; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _cloudsBaseSpeed = 0x590; // Size: 4, Type: float
			constexpr auto _cloudsWindSpeed = 0x594; // Size: 4, Type: float
			constexpr auto _lightningParticleSystem = 0x5a0; // Size: 8, Type: struct UParticleSystem*
			constexpr auto _lightningParticleLifetime = 0x5a8; // Size: 8, Type: struct FFloatInterval
			constexpr auto _thunderSoundEmitter = 0x5b0; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto _thunderSoundDuration = 0x5b8; // Size: 8, Type: struct FFloatInterval
			constexpr auto _lightningRate = 0x5c0; // Size: 4, Type: float
			constexpr auto _lightningMaxDistance = 0x5c4; // Size: 4, Type: float
			constexpr auto _lightningAltitudeOffsetFromPlayer = 0x5c8; // Size: 4, Type: float
			constexpr auto _lightningAltitudeBandThickness = 0x5cc; // Size: 4, Type: float
			constexpr auto _precipitationEmittersRoot = 0x5f0; // Size: 8, Type: struct USceneComponent*
			constexpr auto _precipitationMaskCapture = 0x5f8; // Size: 8, Type: struct UChildActorComponent*
			constexpr auto _precipitationMaskUpdateInterval = 0x600; // Size: 4, Type: float
			constexpr auto _precipitationEmittersUpOffset = 0x608; // Size: 4, Type: float
			constexpr auto _precipitationEmittersForwardOffset = 0x60c; // Size: 4, Type: float
			constexpr auto _precipitationEmittersVelocityOffset = 0x610; // Size: 4, Type: float
			constexpr auto _rainParticleSystems = 0x618; // Size: 16, Type: struct TArray<struct UParticleSystem*>
			constexpr auto _rainEmitters = 0x628; // Size: 16, Type: struct TArray<struct UParticleSystemComponent*>
			constexpr auto _rainIntensity = 0x638; // Size: 4, Type: float
			constexpr auto _maxRainMilimeterPerHour = 0x63c; // Size: 4, Type: float
			constexpr auto _snowParticleSystems = 0x640; // Size: 16, Type: struct TArray<struct UParticleSystem*>
			constexpr auto _snowEmitters = 0x650; // Size: 16, Type: struct TArray<struct UParticleSystemComponent*>
			constexpr auto _snowIntensity = 0x660; // Size: 4, Type: float
			constexpr auto _mainMPC = 0x668; // Size: 8, Type: struct UMaterialParameterCollection*
			constexpr auto _foliageMPC = 0x670; // Size: 8, Type: struct UMaterialParameterCollection*
			constexpr auto _foliageMPCSubsurfaceColorIntensityCurve = 0x678; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _wetnessMPC = 0x700; // Size: 8, Type: struct UMaterialParameterCollection*
			constexpr auto _wetnessMPCEmissiveIntensityCurve = 0x708; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _particlesMPC = 0x790; // Size: 8, Type: struct UMaterialParameterCollection*
			constexpr auto _particlesMPCGlobalParticlesColorCurve = 0x798; // Size: 520, Type: struct FRuntimeCurveLinearColor
			constexpr auto _baseAirTemperature = 0x9a0; // Size: 4, Type: float
			constexpr auto _baseAirTemperatureRange = 0x9a4; // Size: 8, Type: struct FFloatInterval
			constexpr auto _airTemperatureHeightModifier = 0x9ac; // Size: 4, Type: float
			constexpr auto _waterTemperature = 0x9b0; // Size: 4, Type: float
			constexpr auto _waterTemperatureRange = 0x9b4; // Size: 8, Type: struct FFloatInterval
			constexpr auto _waterTemperatureInterpSpeed = 0x9bc; // Size: 4, Type: float
			constexpr auto _waterTemperatureHeightModifier = 0x9c0; // Size: 4, Type: float
			constexpr auto _temperatureDifferenceBetweenShadeAndOnSun = 0x9c4; // Size: 4, Type: float
			constexpr auto _waterEvaporationRate = 0x9c8; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _airRelativeHumidity = 0xa50; // Size: 4, Type: float
			constexpr auto _windSourceComponent = 0xa58; // Size: 8, Type: struct UWindDirectionalSourceComponent*
			constexpr auto _leavesComponent = 0xa60; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto _windAzimuth = 0xa68; // Size: 4, Type: float
			constexpr auto _windIntensity = 0xa6c; // Size: 4, Type: float
			constexpr auto _windAzimuthForWaves = 0xa70; // Size: 4, Type: float
			constexpr auto _windIntensityForWaves = 0xa74; // Size: 4, Type: float
			constexpr auto _maxWindSpeedKph = 0xa78; // Size: 4, Type: float
			constexpr auto _heightFog = 0xa80; // Size: 8, Type: struct UExponentialHeightFogComponent*
			constexpr auto _fogDensity = 0xa88; // Size: 4, Type: float
			constexpr auto _fogFalloff = 0xa8c; // Size: 4, Type: float
			constexpr auto _fogHeightOffset = 0xa90; // Size: 4, Type: float
			constexpr auto _fogBaseInscatteringColor = 0xa94; // Size: 16, Type: struct FLinearColor
			constexpr auto _fogBaseDirectionalInscatteringColor = 0xaa4; // Size: 16, Type: struct FLinearColor
			constexpr auto _postProcessVolume = 0xab8; // Size: 8, Type: struct UChildActorComponent*
			constexpr auto _exposureMinBrightness = 0xac0; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _exposureMaxBrightness = 0xb48; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _exposureSpeedUp = 0xbd0; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _exposureSpeedDown = 0xc58; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _windAzimuthRandom = 0xce0; // Size: 104, Type: struct FMultistageRandomRoll
			constexpr auto _windIntensityRandom = 0xd48; // Size: 104, Type: struct FMultistageRandomRoll
			constexpr auto _cirrostratusCoverageRandom = 0xdb0; // Size: 104, Type: struct FMultistageRandomRoll
			constexpr auto _cumulonimbusCoverageRandom = 0xe18; // Size: 104, Type: struct FMultistageRandomRoll
			constexpr auto _nimbostratusCoverageRandom = 0xe80; // Size: 104, Type: struct FMultistageRandomRoll
			constexpr auto _baseAirTemperatureVsTimeOfDay = 0xee8; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _fogDensityVsSunIntensity = 0xf70; // Size: 136, Type: struct FRuntimeFloatCurve
			constexpr auto _fogDensityFromCumulonimbus = 0xff8; // Size: 4, Type: float
			constexpr auto _fogRainRatioFromCumulonimbus = 0xffc; // Size: 4, Type: float
			constexpr auto _fogDensityWhenRaining = 0x1004; // Size: 4, Type: float
			constexpr auto _fogDensityInterpSpeed = 0x1008; // Size: 4, Type: float
			constexpr auto _autoSaveInterval = 0x100c; // Size: 4, Type: float
			constexpr auto _shouldSerializeState = 0x1014; // Size: 1, Type: bool
			constexpr auto _sendReplicatedStateSnapshotInterval = 0x1018; // Size: 4, Type: float
			constexpr auto _nighttimeDarkness = 0x103c; // Size: 4, Type: float
	}
} 
