namespace offsets
{
	namespace UAdminCommandArgumentCompletion_Enum
	{
			constexpr auto _enum = 0x38; // Size: 8, Type: struct FName
			constexpr auto _excludeNoneEnumerator = 0x40; // Size: 1, Type: bool
			constexpr auto _excludeCountEnumerator = 0x41; // Size: 1, Type: bool
			constexpr auto _excludeAutoGeneratedEnumerator = 0x42; // Size: 1, Type: bool
			constexpr auto _additionalEnumeratorsToExclude = 0x48; // Size: 80, Type: struct TSet<struct FName>
	}
} 
