namespace offsets
{
	namespace UDataSingleton
	{
			constexpr auto ImpulseMultipliers = 0x28; // Size: 16, Type: struct TArray<struct FProjectileImpulseMultiplier>
			constexpr auto CrosshairIconUp = 0x38; // Size: 24, Type: struct FCanvasIcon
			constexpr auto CrosshairIconDown = 0x50; // Size: 24, Type: struct FCanvasIcon
			constexpr auto CrosshairIconLeft = 0x68; // Size: 24, Type: struct FCanvasIcon
			constexpr auto CrosshairIconRight = 0x80; // Size: 24, Type: struct FCanvasIcon
			constexpr auto CrosshairIconCenter = 0x98; // Size: 24, Type: struct FCanvasIcon
			constexpr auto CrosshairIconCenterThrowing = 0xb0; // Size: 24, Type: struct FCanvasIcon
			constexpr auto CrosshairBlockedIcon = 0xc8; // Size: 24, Type: struct FCanvasIcon
			constexpr auto BowSpreadCircle = 0xe0; // Size: 24, Type: struct FCanvasIcon
			constexpr auto SingleFireIcon = 0xf8; // Size: 8, Type: struct UTexture2D*
			constexpr auto AutoFireIcon = 0x100; // Size: 8, Type: struct UTexture2D*
			constexpr auto BurstFireIcon = 0x108; // Size: 8, Type: struct UTexture2D*
			constexpr auto WeaponSpreadBase = 0x110; // Size: 4, Type: float
			constexpr auto WeaponSpreadData[9] = 0x114; // Size: 576, Type: struct FWeaponSpreadData
			constexpr auto BowArrowDeviationDegreesAngleByStep = 0x354; // Size: 4, Type: float
			constexpr auto WeaponViewKickData[9] = 0x358; // Size: 216, Type: struct FWeaponViewKickData
			constexpr auto WeaponAimingAutoCorrectAngle = 0x430; // Size: 4, Type: float
			constexpr auto WeaponMalfunctionProbabilityCurves = 0x438; // Size: 952, Type: struct FWeaponMalfunctionProbabilityCurves
			constexpr auto UpperBoundStaminaAmountToDrain = 0x7f0; // Size: 4, Type: float
			constexpr auto LowerBoundWeaponWeightForStaminaDrain = 0x7f4; // Size: 4, Type: float
			constexpr auto UpperBoundWeaponWeightForStaminaDrain = 0x7f8; // Size: 4, Type: float
			constexpr auto FOVFirstPersonMultiplierRange = 0x7fc; // Size: 8, Type: struct FFloatInterval
			constexpr auto FOVThirdPersonMultiplierRange = 0x804; // Size: 8, Type: struct FFloatInterval
			constexpr auto FOVFirstPersonDrivingMultiplierRange = 0x80c; // Size: 8, Type: struct FFloatInterval
			constexpr auto FOVThirdPersonDrivingMultiplierRange = 0x814; // Size: 8, Type: struct FFloatInterval
			constexpr auto WeaponFOVWhileScoping = 0x81c; // Size: 4, Type: float
			constexpr auto DownTheSightsModeLerpCurve = 0x820; // Size: 8, Type: struct UCurveFloat*
			constexpr auto WeaponFOVParameterCollection = 0x828; // Size: 8, Type: struct UMaterialParameterCollection*
			constexpr auto LoadMagazineSpeedModifierSkillFactor = 0x830; // Size: 8, Type: struct FFloatInterval
			constexpr auto LoadMagazineSpeedModifierDexterityFactor = 0x838; // Size: 8, Type: struct FFloatInterval
			constexpr auto InteractIcon = 0x840; // Size: 24, Type: struct FCanvasIcon
			constexpr auto BondageIcon = 0x858; // Size: 24, Type: struct FCanvasIcon
			constexpr auto DefaultInputData = 0x870; // Size: 8, Type: struct UInputDataAsset*
			constexpr auto Widgets = 0x878; // Size: 8, Type: struct UDerivedWidgetsData*
			constexpr auto PlaceablePrimaryMatValid = 0x880; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto PlaceablePrimaryMatInvalid = 0x888; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto PlaceablePrimaryMatFriendlyFlag = 0x890; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto PlaceableOutlineMat = 0x898; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto PlaceableDepthMat = 0x8a0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto PlaceableMaterialRadiusSphere = 0x8a8; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto ItemPlacementMatValid = 0x8b0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto ItemPlacementMatInvalid = 0x8b8; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto WidgetMaterial = 0x8c0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto ToolBoxItemTag = 0x8c8; // Size: 8, Type: struct UBaseItemTag*
			constexpr auto MushroomItemTag = 0x8d0; // Size: 8, Type: struct UBaseItemTag*
			constexpr auto AlcoholItemTag = 0x8d8; // Size: 8, Type: struct UBaseItemTag*
			constexpr auto SoapItemTag = 0x8e0; // Size: 8, Type: struct UBaseItemTag*
			constexpr auto AnimalSkinItemClass = 0x8e8; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto TrapData = 0x910; // Size: 8, Type: struct UTrapData*
			constexpr auto DogTagItemClass = 0x918; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto ClothesItemChoppingRecipeIngredientsClassesToReplaceWhenDirty = 0x940; // Size: 80, Type: struct TMap<struct TSoftClassPtr<UObject>, struct TSoftClassPtr<UObject>>
			constexpr auto ItemGeneralParametersDataTable = 0x990; // Size: 8, Type: struct UDataTable*
			constexpr auto ItemSpawningParametersTable = 0x998; // Size: 40, Type: struct TSoftObjectPtr<UDataTable>
			constexpr auto ItemObstructionCollisionChannel = 0x9c0; // Size: 1, Type: char ECollisionChannel
			constexpr auto ShouldTraceComplexCollisionForItemObstruction = 0x9c1; // Size: 1, Type: bool
			constexpr auto AssetsHiddenFromAdminCommands = 0x9c8; // Size: 80, Type: struct TSet<struct FPrimaryAssetId>
			constexpr auto MissonDataGroup = 0xa18; // Size: 8, Type: struct UMissionDataGroup*
			constexpr auto DialogueData = 0xa20; // Size: 8, Type: struct UDialogueData*
			constexpr auto VoiceSoundClass = 0xa28; // Size: 8, Type: struct USoundClass*
			constexpr auto NetworkDataIdAsset = 0xa30; // Size: 8, Type: struct UNetworkDataIdAsset*
			constexpr auto WashClothesData = 0xa38; // Size: 8, Type: struct UWashClothesData*
			constexpr auto DecontaminateData = 0xa40; // Size: 8, Type: struct UDecontaminateData*
			constexpr auto BuryData = 0xa48; // Size: 8, Type: struct UBuryData*
			constexpr auto SquadEmblemData = 0xa50; // Size: 8, Type: struct UEmblemData*
			constexpr auto ItemTetrisMaterial = 0xa58; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto PhysicalSurfaceEffectsData = 0xa60; // Size: 8, Type: struct UPhysicalSurfacesEffectsData*
			constexpr auto ChestLockedIcon = 0xa68; // Size: 8, Type: struct UTexture2D*
			constexpr auto ChestUnlockedIcon = 0xa70; // Size: 8, Type: struct UTexture2D*
			constexpr auto ChestLockingSound = 0xa78; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto UIData = 0xa80; // Size: 8, Type: UGlobalUIData*
			constexpr auto WaterSplashParticleSystem = 0xa88; // Size: 8, Type: struct UParticleSystem*
			constexpr auto WaterSplashAudioEvent = 0xa90; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto SurfaceHardnessData = 0xa98; // Size: 8, Type: struct USurfaceHardnessData*
			constexpr auto DamageData = 0xaa0; // Size: 8, Type: struct UDamageData*
			constexpr auto DefaultDamageCustomizationClass = 0xaa8; // Size: 8, Type: UDamageCustomization*
			constexpr auto LandingDamageCustomizationClass = 0xab0; // Size: 8, Type: UDamageCustomization*
			constexpr auto BackpackCharacterMeshClass = 0xab8; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto RainWaterResourceClass = 0xae0; // Size: 8, Type: UGameResourceType*
			constexpr auto GameResourceMixingRules = 0xae8; // Size: 16, Type: struct TArray<struct FGameResourceMixingRule>
			constexpr auto WaterSurfaceType = 0xaf8; // Size: 1, Type: char EPhysicalSurface
			constexpr auto TransactionCompleteSound = 0xb00; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto GenderEnumVsGenderTagMapping[3] = 0xbf0; // Size: 24, Type: struct FGameplayTag
			constexpr auto SurgeryRoomClass = 0xc08; // Size: 8, Type: ASurgeryRoom*
			constexpr auto BarberShopClass = 0xc10; // Size: 8, Type: ABarberShop*
			constexpr auto DefaultPrisonerCommonData = 0xc18; // Size: 8, Type: UPrisonerCommonData*
			constexpr auto PrisonerAppearanceSet = 0xc20; // Size: 8, Type: struct UPrisonerAppearanceSetDataAsset*
			constexpr auto CookingCommonData = 0xc28; // Size: 8, Type: struct UCookingCommonData*
			constexpr auto CookingRecipeRegistry = 0xc30; // Size: 8, Type: struct UCookingRecipeRegistry*
			constexpr auto CookingUtilityUIDataTable = 0xc38; // Size: 40, Type: struct TSoftObjectPtr<UDataTable>
			constexpr auto FamePointSettings = 0xc60; // Size: 8, Type: struct UFamePointSettings*
			constexpr auto AlwaysFunctioningVehicles = 0xc68; // Size: 16, Type: struct TArray<struct FPrimaryAssetId>
			constexpr auto DefaultEntitySystemSettings = 0xc78; // Size: 8, Type: UEntitySystemSettings*
			constexpr auto _cookingUtilityTagToUIDataTable = 0xcd8; // Size: 8, Type: struct UDataTable*
			constexpr auto _noiseLevelValues[6] = 0xce0; // Size: 24, Type: float
			constexpr auto _teamAttitudes[7] = 0xcf8; // Size: 49, Type: struct FAITeamAttitudeData
			constexpr auto _economyTradeablesDataTable = 0xd80; // Size: 8, Type: struct UDataTable*
			constexpr auto _economySpecificData = 0xd88; // Size: 8, Type: struct UEconomySpecificData*
	}
} 
