namespace offsets
{
	namespace UPrimitiveComponent
	{
			constexpr auto MinDrawDistance = 0x200; // Size: 4, Type: float
			constexpr auto UseHLODMinDrawDistance = 0x204; // Size: 1, Type: bool
			constexpr auto LDMaxDrawDistance = 0x208; // Size: 4, Type: float
			constexpr auto CachedMaxDrawDistance = 0x20c; // Size: 4, Type: float
			constexpr auto DepthPriorityGroup = 0x210; // Size: 1, Type: char ESceneDepthPriorityGroup
			constexpr auto ViewOwnerDepthPriorityGroup = 0x211; // Size: 1, Type: char ESceneDepthPriorityGroup
			constexpr auto IndirectLightingCacheQuality = 0x212; // Size: 1, Type: char EIndirectLightingCacheQuality
			constexpr auto LightmapType = 0x213; // Size: 1, Type: uint8_t 
			constexpr auto bUseMaxLODAsImposter = 0x214; // Size: 1, Type: char
			constexpr auto bBatchImpostersAsInstances = 0x214; // Size: 1, Type: char
			constexpr auto bNeverDistanceCull = 0x214; // Size: 1, Type: char
			constexpr auto bAlwaysCreatePhysicsState = 0x214; // Size: 1, Type: char
			constexpr auto bGenerateOverlapEvents = 0x215; // Size: 1, Type: char
			constexpr auto bMultiBodyOverlap = 0x215; // Size: 1, Type: char
			constexpr auto bTraceComplexOnMove = 0x215; // Size: 1, Type: char
			constexpr auto bReturnMaterialOnMove = 0x215; // Size: 1, Type: char
			constexpr auto bUseViewOwnerDepthPriorityGroup = 0x215; // Size: 1, Type: char
			constexpr auto bAllowCullDistanceVolume = 0x215; // Size: 1, Type: char
			constexpr auto bHasMotionBlurVelocityMeshes = 0x215; // Size: 1, Type: char
			constexpr auto bVisibleInReflectionCaptures = 0x215; // Size: 1, Type: char
			constexpr auto bVisibleInRealTimeSkyCaptures = 0x216; // Size: 1, Type: char
			constexpr auto bVisibleInRayTracing = 0x216; // Size: 1, Type: char
			constexpr auto bRenderInMainPass = 0x216; // Size: 1, Type: char
			constexpr auto bRenderInDepthPass = 0x216; // Size: 1, Type: char
			constexpr auto bReceivesDecals = 0x216; // Size: 1, Type: char
			constexpr auto bOwnerNoSee = 0x216; // Size: 1, Type: char
			constexpr auto bOnlyOwnerSee = 0x216; // Size: 1, Type: char
			constexpr auto bTreatAsBackgroundForOcclusion = 0x216; // Size: 1, Type: char
			constexpr auto bUseAsOccluder = 0x217; // Size: 1, Type: char
			constexpr auto bSelectable = 0x217; // Size: 1, Type: char
			constexpr auto bForceMipStreaming = 0x217; // Size: 1, Type: char
			constexpr auto bHasPerInstanceHitProxies = 0x217; // Size: 1, Type: char
			constexpr auto CastShadow = 0x217; // Size: 1, Type: char
			constexpr auto bAffectDynamicIndirectLighting = 0x217; // Size: 1, Type: char
			constexpr auto bAffectDistanceFieldLighting = 0x217; // Size: 1, Type: char
			constexpr auto bCastDynamicShadow = 0x217; // Size: 1, Type: char
			constexpr auto bCastStaticShadow = 0x218; // Size: 1, Type: char
			constexpr auto bCastVolumetricTranslucentShadow = 0x218; // Size: 1, Type: char
			constexpr auto bCastContactShadow = 0x218; // Size: 1, Type: char
			constexpr auto bSelfShadowOnly = 0x218; // Size: 1, Type: char
			constexpr auto bCastFarShadow = 0x218; // Size: 1, Type: char
			constexpr auto bCastInsetShadow = 0x218; // Size: 1, Type: char
			constexpr auto bCastCinematicShadow = 0x218; // Size: 1, Type: char
			constexpr auto bCastHiddenShadow = 0x218; // Size: 1, Type: char
			constexpr auto bCastShadowAsTwoSided = 0x219; // Size: 1, Type: char
			constexpr auto bLightAsIfStatic = 0x219; // Size: 1, Type: char
			constexpr auto bLightAttachmentsAsGroup = 0x219; // Size: 1, Type: char
			constexpr auto bExcludeFromLightAttachmentGroup = 0x219; // Size: 1, Type: char
			constexpr auto bReceiveMobileCSMShadows = 0x219; // Size: 1, Type: char
			constexpr auto bSingleSampleShadowFromStationaryLights = 0x219; // Size: 1, Type: char
			constexpr auto bIgnoreRadialImpulse = 0x219; // Size: 1, Type: char
			constexpr auto bIgnoreRadialForce = 0x219; // Size: 1, Type: char
			constexpr auto bApplyImpulseOnDamage = 0x21a; // Size: 1, Type: char
			constexpr auto bReplicatePhysicsToAutonomousProxy = 0x21a; // Size: 1, Type: char
			constexpr auto bFillCollisionUnderneathForNavmesh = 0x21a; // Size: 1, Type: char
			constexpr auto AlwaysLoadOnClient = 0x21a; // Size: 1, Type: char
			constexpr auto AlwaysLoadOnServer = 0x21a; // Size: 1, Type: char
			constexpr auto bUseEditorCompositing = 0x21a; // Size: 1, Type: char
			constexpr auto bRenderCustomDepth = 0x21a; // Size: 1, Type: char
			constexpr auto bVisibleInSceneCaptureOnly = 0x21a; // Size: 1, Type: char
			constexpr auto bHiddenInSceneCapture = 0x21b; // Size: 1, Type: char
			constexpr auto bHasCustomNavigableGeometry = 0x21c; // Size: 1, Type: char EHasCustomNavigableGeometry
			constexpr auto CanCharacterStepUpOn = 0x21e; // Size: 1, Type: char ECanBeCharacterBase
			constexpr auto LightingChannels = 0x21f; // Size: 1, Type: struct FLightingChannels
			constexpr auto CustomDepthStencilWriteMask = 0x220; // Size: 1, Type: uint8_t 
			constexpr auto CustomDepthStencilValue = 0x224; // Size: 4, Type: int32_t
			constexpr auto CustomPrimitiveData = 0x228; // Size: 16, Type: struct FCustomPrimitiveData
			constexpr auto CustomPrimitiveDataInternal = 0x238; // Size: 16, Type: struct FCustomPrimitiveData
			constexpr auto TranslucencySortPriority = 0x250; // Size: 4, Type: int32_t
			constexpr auto TranslucencySortDistanceOffset = 0x254; // Size: 4, Type: float
			constexpr auto VisibilityId = 0x258; // Size: 4, Type: int32_t
			constexpr auto RuntimeVirtualTextures = 0x260; // Size: 16, Type: struct TArray<struct URuntimeVirtualTexture*>
			constexpr auto VirtualTextureLodBias = 0x270; // Size: 1, Type: int8_t
			constexpr auto VirtualTextureCullMips = 0x271; // Size: 1, Type: int8_t
			constexpr auto VirtualTextureMinCoverage = 0x272; // Size: 1, Type: int8_t
			constexpr auto VirtualTextureRenderPassType = 0x273; // Size: 1, Type: uint8_t 
			constexpr auto LpvBiasMultiplier = 0x278; // Size: 4, Type: float
			constexpr auto BoundsScale = 0x284; // Size: 4, Type: float
			constexpr auto MoveIgnoreActors = 0x298; // Size: 16, Type: struct TArray<struct AActor*>
			constexpr auto MoveIgnoreComponents = 0x2a8; // Size: 16, Type: struct TArray<struct UPrimitiveComponent*>
			constexpr auto BodyInstance = 0x2c8; // Size: 344, Type: struct FBodyInstance
			constexpr auto OnComponentHit = 0x420; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnComponentBeginOverlap = 0x421; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnComponentEndOverlap = 0x422; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnComponentWake = 0x423; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnComponentSleep = 0x424; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnBeginCursorOver = 0x426; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnEndCursorOver = 0x427; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnClicked = 0x428; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnReleased = 0x429; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnInputTouchBegin = 0x42a; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnInputTouchEnd = 0x42b; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnInputTouchEnter = 0x42c; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnInputTouchLeave = 0x42d; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto LODParentPrimitive = 0x448; // Size: 8, Type: struct UPrimitiveComponent*
	}
} 
