namespace offsets
{
	namespace UPrisonerCommonData
	{
			constexpr auto FemaleAnimationInstance = 0x30; // Size: 8, Type: UAnimInstance*
			constexpr auto MaleAnimationInstance = 0x38; // Size: 8, Type: UAnimInstance*
			constexpr auto ExhaustionRange = 0x40; // Size: 8, Type: struct FFloatInterval
			constexpr auto ExhaustionDamageMultiplier = 0x48; // Size: 4, Type: float
			constexpr auto SkinHardness = 0x4c; // Size: 4, Type: float
			constexpr auto LastDamageDealerResetTime = 0x50; // Size: 4, Type: float
			constexpr auto StrengthMeleeDamageMultiplierRange = 0x54; // Size: 8, Type: struct FFloatInterval
			constexpr auto ExhaustionMeleeDamageMultiplier = 0x5c; // Size: 4, Type: float
			constexpr auto ClothesPartUsedByMeleeAttackCapsuleAttachment = 0x60; // Size: 80, Type: struct TMap<struct FGameplayTag, uint8_t >
			constexpr auto AttackerBoneByMeleeAttackCapsuleAttachment = 0xb0; // Size: 80, Type: struct TMap<struct FGameplayTag, struct FName>
			constexpr auto UnarmedAttackBaseEnergy = 0x100; // Size: 4, Type: float
			constexpr auto StrengthThrowingDamageMultiplierRange = 0x104; // Size: 8, Type: struct FFloatInterval
			constexpr auto ExhaustionThrowingDamageMultiplier = 0x10c; // Size: 4, Type: float
			constexpr auto NoSkillThrowingDamageMultiplier = 0x110; // Size: 4, Type: float
			constexpr auto BasicSkillThrowingDamageMultiplier = 0x114; // Size: 4, Type: float
			constexpr auto MediumSkillThrowingDamageMultiplier = 0x118; // Size: 4, Type: float
			constexpr auto AdvancedSkillThrowingDamageMultiplier = 0x11c; // Size: 4, Type: float
			constexpr auto AboveAdvancedSkillThrowingDamageMultiplier = 0x120; // Size: 4, Type: float
			constexpr auto ThrowEnergyRange = 0x124; // Size: 8, Type: struct FFloatInterval
			constexpr auto MaxActorEyesOffsetWhenLeaning = 0x12c; // Size: 4, Type: float
			constexpr auto DefaultMeshTransform = 0x130; // Size: 48, Type: struct FTransform
			constexpr auto NumberOfCrouchStages = 0x160; // Size: 4, Type: int32_t
			constexpr auto CrouchStagesInterpSpeed = 0x164; // Size: 4, Type: float
			constexpr auto CrouchViewsAdditionalGlobalOffsetZVsCrouchStage = 0x168; // Size: 8, Type: struct UCurveFloat*
			constexpr auto ProneEyeHeight = 0x170; // Size: 4, Type: float
			constexpr auto ProneEyeForwardOffset = 0x174; // Size: 4, Type: float
			constexpr auto SittingOnGroundEyeHeight = 0x178; // Size: 4, Type: float
			constexpr auto LyingOnGroundEyeHeight = 0x17c; // Size: 4, Type: float
			constexpr auto RestingOnGroundBackwardOffset = 0x180; // Size: 4, Type: float
			constexpr auto DefaultPace = 0x184; // Size: 1, Type: uint8_t 
			constexpr auto MovementSettings = 0x188; // Size: 8, Type: struct UPrisonerMovementSettings*
			constexpr auto DefaultViewBlendDuration = 0x190; // Size: 4, Type: float
			constexpr auto MinEyesRotationYaw = 0x194; // Size: 4, Type: float
			constexpr auto MaxEyesRotationYaw = 0x198; // Size: 4, Type: float
			constexpr auto MinEyesRotationPitch = 0x19c; // Size: 4, Type: float
			constexpr auto MaxEyesRotationPitch = 0x1a0; // Size: 4, Type: float
			constexpr auto MinEyesRotationPitchCurve = 0x1a8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto MaxEyesRotationPitchCurve = 0x1b0; // Size: 8, Type: struct UCurveFloat*
			constexpr auto EyesRotationSpeed = 0x1b8; // Size: 4, Type: float
			constexpr auto DebugEyesRotation = 0x1bc; // Size: 1, Type: bool
			constexpr auto ComaAudioEvent = 0x1c0; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto ComaScreamAudioEvent = 0x1c8; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto DeathAudioEvent = 0x1d0; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto DeathScreamAudioEvent = 0x1d8; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto ColdBreathParticles = 0x1e0; // Size: 8, Type: struct UParticleSystem*
			constexpr auto ColdBreathParticlesAttachPointName = 0x1e8; // Size: 8, Type: struct FName
			constexpr auto StandardUndershirtMaterial = 0x1f0; // Size: 8, Type: struct UMaterialInstance*
			constexpr auto DeluxeUndershirtMaterial = 0x1f8; // Size: 8, Type: struct UMaterialInstance*
			constexpr auto JumpAudioEvent = 0x200; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto LandingImpactHorizontalSpeedWeight = 0x208; // Size: 4, Type: float
			constexpr auto LandingImpactVerticalSpeedWeight = 0x20c; // Size: 4, Type: float
			constexpr auto LandingStaminaDrainCurve = 0x210; // Size: 8, Type: struct UCurveFloat*
			constexpr auto LandingEffects = 0x218; // Size: 8, Type: struct ULandingEffects*
			constexpr auto WaterParticlesWhenIdle = 0x220; // Size: 8, Type: struct UParticleSystem*
			constexpr auto WaterParticlesWhenIdleInOcean = 0x228; // Size: 8, Type: struct UParticleSystem*
			constexpr auto WaterParticlesWhenMoving = 0x230; // Size: 8, Type: struct UParticleSystem*
			constexpr auto WaterParticlesWhenMovingInOcean = 0x238; // Size: 8, Type: struct UParticleSystem*
			constexpr auto WaterParticlesWhenDiving = 0x240; // Size: 8, Type: struct UParticleSystem*
			constexpr auto WaterParticlesWhenDivingAttachPointName = 0x248; // Size: 8, Type: struct FName
			constexpr auto WaterContactParticles = 0x250; // Size: 8, Type: struct UParticleSystem*
			constexpr auto WaterContactParticlesAttachPointName = 0x258; // Size: 8, Type: struct FName
			constexpr auto MinVelocityZToSpawnWaterContactParticles = 0x260; // Size: 4, Type: float
			constexpr auto BuoyancyMultiplierVsGearWeightLimitDeviation = 0x268; // Size: 8, Type: struct UCurveFloat*
			constexpr auto StartedDivingAudioEvent = 0x270; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto StoppedDivingAudioEvent = 0x278; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto EndDivingOnPlayAudioEvent = 0x280; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto MaxHeadWaterWeight = 0x288; // Size: 4, Type: float
			constexpr auto MaxUpperBodyWaterWeight = 0x28c; // Size: 4, Type: float
			constexpr auto MaxLowerBodyWaterWeight = 0x290; // Size: 4, Type: float
			constexpr auto MaxFeetWaterWeight = 0x294; // Size: 4, Type: float
			constexpr auto OutwardsWaterPropagationFactor = 0x298; // Size: 4, Type: float
			constexpr auto InwardsWaterPropagationRate = 0x29c; // Size: 4, Type: float
			constexpr auto OutwardsWaterPropagationRate = 0x2a0; // Size: 4, Type: float
			constexpr auto GettingDryRateVsSpeed = 0x2a8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto SmallBleedingEffect = 0x2b0; // Size: 8, Type: struct UParticleSystem*
			constexpr auto LargeBleedingEffect = 0x2b8; // Size: 8, Type: struct UParticleSystem*
			constexpr auto UrineParticles = 0x2c0; // Size: 8, Type: struct UParticleSystem*
			constexpr auto UrineParticlesAttachPointName = 0x2c8; // Size: 8, Type: struct FName
			constexpr auto UrineParticlesAttachPointSmallestName = 0x2d0; // Size: 8, Type: struct FName
			constexpr auto UrineParticlesAttachPointBiggestName = 0x2d8; // Size: 8, Type: struct FName
			constexpr auto UrineParticlesAttachPointFemaleName = 0x2e0; // Size: 8, Type: struct FName
			constexpr auto UrineParticlesAttachPointMaleName = 0x2e8; // Size: 8, Type: struct FName
			constexpr auto DetectNearbyFoliageRadius = 0x2f0; // Size: 4, Type: float
			constexpr auto MinLocationDeltaToUpdateNearbyFoliage = 0x2f4; // Size: 4, Type: float
			constexpr auto MinSpeedToTriggerMovingThroughFoliageEffects = 0x2f8; // Size: 4, Type: float
			constexpr auto MinAngularSpeedToTriggerMovingThroughFoliageEffects = 0x2fc; // Size: 4, Type: float
			constexpr auto ShouldAutomaticallyBeSeenInFoliageByAIDistance = 0x300; // Size: 4, Type: float
			constexpr auto OpenInventoryAudioEvent = 0x308; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto CloseInventoryAudioEvent = 0x310; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto OpenOceanAudioEvent = 0x318; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto CharacterDetectionRadiusForIngameMusic = 0x320; // Size: 4, Type: float
			constexpr auto BulletFlybyDangerCooldown = 0x324; // Size: 4, Type: float
			constexpr auto HeadExplodeDamageThreshold = 0x328; // Size: 4, Type: float
			constexpr auto MeleeDangerCooldown = 0x32c; // Size: 4, Type: float
			constexpr auto MeleeDangerRadius = 0x330; // Size: 4, Type: float
			constexpr auto MeleeDangerAngle = 0x334; // Size: 4, Type: float
			constexpr auto PostReviveStateDuration = 0x338; // Size: 4, Type: float
			constexpr auto HitReactTypeWhenStanding = 0x33c; // Size: 8, Type: struct FGameplayTag
			constexpr auto HitReactTypeWhenStandingInCombatMode = 0x344; // Size: 8, Type: struct FGameplayTag
			constexpr auto HitReactTypeWhenStandingInCombatModeAndHoldingBlock = 0x34c; // Size: 8, Type: struct FGameplayTag
			constexpr auto HitReactTypeWhenCrouching = 0x354; // Size: 8, Type: struct FGameplayTag
			constexpr auto HitReactTypeWhenProne = 0x35c; // Size: 8, Type: struct FGameplayTag
			constexpr auto HitReactTypeWhenCaptured = 0x364; // Size: 8, Type: struct FGameplayTag
			constexpr auto HitReactLandingParamsMap = 0x370; // Size: 80, Type: struct TMap<uint8_t , struct UHitReactLandingParams*>
			constexpr auto MeleeAttackCapsulesAttachmentForItemInLHand = 0x3c0; // Size: 8, Type: struct FGameplayTag
			constexpr auto MeleeAttackCapsulesAttachmentForItemInRHand = 0x3c8; // Size: 8, Type: struct FGameplayTag
			constexpr auto MeleeAttackTypes = 0x3d0; // Size: 136, Type: struct FPrisonerMeleeAttackTypes
			constexpr auto MeleeTargetMaxDistance = 0x458; // Size: 4, Type: float
			constexpr auto MeleeTargetMaxHeightDifference = 0x45c; // Size: 4, Type: float
			constexpr auto MeleeTargetMaxConeHalfAngleVsDistanceToTarget = 0x460; // Size: 8, Type: struct UCurveFloat*
			constexpr auto TimeSpanAfterWhichMeleeAttacksBecomeInitial = 0x468; // Size: 4, Type: float
			constexpr auto MeleeHitRagdollImpulseByDamageMagnitudeType = 0x470; // Size: 80, Type: struct TMap<uint8_t , float>
			constexpr auto DefaultMeleeHitRagdollImpulse = 0x4c0; // Size: 4, Type: float
			constexpr auto ThrowModeActivationDelay = 0x4c4; // Size: 4, Type: float
			constexpr auto ThrowLaunchLocationSocketName = 0x4c8; // Size: 8, Type: struct FName
			constexpr auto ThrowingPathBrightnessFromTimeCurve = 0x4d0; // Size: 8, Type: struct UCurveFloat*
			constexpr auto IslandBoundsCheckInterval = 0x4d8; // Size: 4, Type: float
			constexpr auto PhysicalSurfacesData = 0x4e0; // Size: 8, Type: struct UPhysicalSurfacesData*
			constexpr auto DeluxeWristwatchClass = 0x4e8; // Size: 8, Type: AWristwatch*
			constexpr auto ScopeWidget = 0x4f0; // Size: 8, Type: UWeaponScopeWidget*
			constexpr auto PlaceableActorItemsClass = 0x4f8; // Size: 8, Type: APlaceableActorItems*
			constexpr auto PlaceableActorFortificationsClass = 0x500; // Size: 8, Type: APlaceableActorFortifications*
			constexpr auto PlaceableActorBaseBuildingClass = 0x508; // Size: 8, Type: APlaceableActorBaseBuilding*
			constexpr auto PlaceableActorBaseUpgradeClass = 0x510; // Size: 8, Type: APlaceableActorBaseUpgrade*
			constexpr auto PlaceableActorGardenClass = 0x518; // Size: 8, Type: APlaceableActorGarden*
			constexpr auto PlaceableActorModularBaseBuildingClass = 0x520; // Size: 8, Type: APlaceableActorModularBaseBuilding*
			constexpr auto MaxPossiblePlacedBlueprints = 0x528; // Size: 4, Type: int32_t
			constexpr auto OpenOceanRange = 0x52c; // Size: 4, Type: float
			constexpr auto FeetSlot = 0x530; // Size: 8, Type: struct FGameplayTag
			constexpr auto HairSlot = 0x538; // Size: 8, Type: struct FGameplayTag
			constexpr auto HeadSlot = 0x540; // Size: 8, Type: struct FGameplayTag
			constexpr auto NeckSlot = 0x548; // Size: 8, Type: struct FGameplayTag
			constexpr auto FacialHairSlot = 0x550; // Size: 8, Type: struct FGameplayTag
			constexpr auto PenisSlot = 0x558; // Size: 8, Type: struct FGameplayTag
			constexpr auto ChipSlot = 0x560; // Size: 8, Type: struct FGameplayTag
			constexpr auto LEyeSlot = 0x568; // Size: 8, Type: struct FGameplayTag
			constexpr auto REyeSlot = 0x570; // Size: 8, Type: struct FGameplayTag
			constexpr auto EyewearSlot = 0x578; // Size: 8, Type: struct FGameplayTag
			constexpr auto HandsSlot = 0x580; // Size: 8, Type: struct FGameplayTag
			constexpr auto MaskSlot = 0x588; // Size: 8, Type: struct FGameplayTag
			constexpr auto CensorshipActiveTag = 0x590; // Size: 8, Type: struct FGameplayTag
			constexpr auto PrisonerMountedTag = 0x598; // Size: 8, Type: struct FGameplayTag
			constexpr auto HeadHiddenTag = 0x5a0; // Size: 8, Type: struct FGameplayTag
			constexpr auto HeadExplodedTag = 0x5a8; // Size: 8, Type: struct FGameplayTag
			constexpr auto ShowGenitalsOverrideTag = 0x5b0; // Size: 8, Type: struct FGameplayTag
			constexpr auto BodyCharacterMeshClass = 0x5b8; // Size: 8, Type: UCharacterMesh*
			constexpr auto ClothesCharacterMeshClass = 0x5c0; // Size: 8, Type: UCharacterMesh*
			constexpr auto CensorshipCharacterMeshClass = 0x5c8; // Size: 8, Type: UCharacterMesh*
			constexpr auto ShoesCharacterMeshClasses = 0x5d0; // Size: 16, Type: struct TArray<UCharacterMesh*>
			constexpr auto FaceCoveringCharacterMeshClasses = 0x5e0; // Size: 16, Type: struct TArray<UCharacterMesh*>
			constexpr auto GearSlotsCausingUpperBodyNoise = 0x5f0; // Size: 32, Type: struct FGameplayTagContainer
			constexpr auto LeavingTheIslandPenaltyTimes = 0x610; // Size: 80, Type: struct TMap<uint8_t , float>
			constexpr auto GameEventOutOfBoundsDamage = 0x660; // Size: 4, Type: float
			constexpr auto ItemPlacingMaterialAllowed = 0x668; // Size: 8, Type: struct UMaterialInstance*
			constexpr auto ItemPlacingMaterialDisallowed = 0x670; // Size: 8, Type: struct UMaterialInstance*
			constexpr auto VehicleServiceMaterial = 0x678; // Size: 8, Type: struct UMaterialInstance*
			constexpr auto IkInterpSpeed = 0x680; // Size: 4, Type: float
			constexpr auto CommonParameterCollection = 0x688; // Size: 8, Type: struct UMaterialParameterCollection*
			constexpr auto WeaponSocketName = 0x690; // Size: 8, Type: struct FName
			constexpr auto WeaponHolsterSocketName = 0x698; // Size: 8, Type: struct FName
			constexpr auto SwapWeapons = 0x6a0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SwapItemsThrowingItemToWeapon = 0x6a8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SwapItemsWeaponToThrowingItem = 0x6b0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SwapItemsNotWeaponToNotWeapon = 0x6b8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SwapItemsWeaponToWeapon = 0x6c0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SwapItemsNotWeaponToWeapon = 0x6c8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SwapItemsWeaponToNotWeapon = 0x6d0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto EquipRifleStanding = 0x6d8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto UnequipRifleStanding = 0x6e0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto EquipHandgunStanding = 0x6e8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto UnequipHadgunStanding = 0x6f0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto UrinateMaleMontage = 0x6f8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto UrinateFemaleMontage = 0x700; // Size: 8, Type: struct UAnimMontage*
			constexpr auto UrinateMaleForcedMontage = 0x708; // Size: 8, Type: struct UAnimMontage*
			constexpr auto UrinateFemaleForcedMontage = 0x710; // Size: 8, Type: struct UAnimMontage*
			constexpr auto DefecateMontage = 0x718; // Size: 8, Type: struct UAnimMontage*
			constexpr auto DefecateForcedMontage = 0x720; // Size: 8, Type: struct UAnimMontage*
			constexpr auto VomitMontage = 0x728; // Size: 8, Type: struct UAnimMontage*
			constexpr auto VomitForcedMontage = 0x730; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SearchObject = 0x738; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SearchObjectWhileItemInHands = 0x740; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SearchObjectWhileWeaponInHands = 0x748; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SearchObjectWhenSwimming = 0x750; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SearchPrisoner = 0x758; // Size: 8, Type: struct UAnimMontage*
			constexpr auto PatchWoundsStanding = 0x760; // Size: 8, Type: struct UAnimMontage*
			constexpr auto PatchWoundsCrouching = 0x768; // Size: 8, Type: struct UAnimMontage*
			constexpr auto PatchWoundsProne = 0x770; // Size: 8, Type: struct UAnimMontage*
			constexpr auto PatchWoundsStandingEnd = 0x778; // Size: 8, Type: struct UAnimMontage*
			constexpr auto PatchWoundsCrouchingEnd = 0x780; // Size: 8, Type: struct UAnimMontage*
			constexpr auto PatchWoundsProneEnd = 0x788; // Size: 8, Type: struct UAnimMontage*
			constexpr auto EatGeneric = 0x790; // Size: 8, Type: struct UAnimMontage*
			constexpr auto EatCan = 0x798; // Size: 8, Type: struct UAnimMontage*
			constexpr auto DrinkFromBottleStanding = 0x7a0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto DrinkFromBottleCrouching = 0x7a8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto DrinkInteraction = 0x7b0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto DefaultLongThrowMontage = 0x7b8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto DefaultLongThrowLoopMontage = 0x7c0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto DefaultShortThrowMontage = 0x7c8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto DefaultThrowbackGrenadeMontage = 0x7d0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto ChopTreeStanding = 0x7d8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto ChopTreeStandingEnd = 0x7e0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto ChopLogStanding = 0x7e8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto ChopLogStandingEnd = 0x7f0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BreakStone = 0x7f8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BreakStoneEnd = 0x800; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CraftStanding = 0x808; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CraftCrouching = 0x810; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CraftProne = 0x818; // Size: 8, Type: struct UAnimMontage*
			constexpr auto UncraftStanding = 0x820; // Size: 8, Type: struct UAnimMontage*
			constexpr auto UncraftCrouching = 0x828; // Size: 8, Type: struct UAnimMontage*
			constexpr auto UncraftProne = 0x830; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CheckTime = 0x838; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CheckTimeFemale = 0x840; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CheckTimeWhileItemInHands = 0x848; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CheckTimeWhileItemInHandsFemale = 0x850; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CheckTimeWhileWeaponInHands = 0x858; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CheckTimeWhileWeaponInHandsFemale = 0x860; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CheckTemperature = 0x868; // Size: 8, Type: struct UAnimMontage*
			constexpr auto ForceUnlockStanding = 0x870; // Size: 8, Type: struct UAnimMontage*
			constexpr auto ForceUnlockStandingEnd = 0x878; // Size: 8, Type: struct UAnimMontage*
			constexpr auto ForceUnlockStandingStop = 0x880; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SpillMontage = 0x888; // Size: 8, Type: struct UAnimMontage*
			constexpr auto StompOutFireMontage = 0x890; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BlowAirIntoFireMontage = 0x898; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BlowAirIntoLowFireMontage = 0x8a0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureShowFinger = 0x8a8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureStandSurrender = 0x8b0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureWaveHi = 0x8b8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureYouAreDead = 0x8c0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureFY = 0x8c8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GesturePoint = 0x8d0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureHeart = 0x8d8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureBallpalm = 0x8e0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureFacepalm = 0x8e8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureFingerGun = 0x8f0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureLaughing = 0x8f8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureSmellWave = 0x900; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureSquat = 0x908; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureCharge = 0x910; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureChargeCombat = 0x918; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureFreeze = 0x920; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureFreezeCombat = 0x928; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureGetDown = 0x930; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureGetDownCombat = 0x938; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureGetUp = 0x940; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureGetUpCombat = 0x948; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureHalt = 0x950; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureHaltCombat = 0x958; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureHurryUp = 0x960; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureHurryUpCombat = 0x968; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GesturePointMe = 0x970; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GesturePointMeCombat = 0x978; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GesturePointYou = 0x980; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GesturePointYouCombat = 0x988; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureRally = 0x990; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureRallyCombat = 0x998; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureThumbsUp = 0x9a0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureThumbsUpCombat = 0x9a8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureThumbsDown = 0x9b0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureThumbsDownCombat = 0x9b8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureUnderstandNot = 0x9c0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureUnderstandNotCombat = 0x9c8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureUnderstandYes = 0x9d0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto GestureUnderstandYesCombat = 0x9d8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CommitSuicideStanding = 0x9e0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CommitSuicideCrouching = 0x9e8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto CommitSuicideRareStanding = 0x9f0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto LockpickRegular = 0x9f8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto WhistleMontageMale = 0xa00; // Size: 8, Type: struct UAnimMontage*
			constexpr auto WhistleMontageFemale = 0xa08; // Size: 8, Type: struct UAnimMontage*
			constexpr auto TuneBowMontage = 0xa10; // Size: 8, Type: struct UAnimMontage*
			constexpr auto RepairVehicleMontage = 0xa18; // Size: 8, Type: struct UAnimMontage*
			constexpr auto WashClothMontage = 0xa20; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BuryStandingMontage = 0xa28; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BuryRestStandingMontage = 0xa30; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BuryResumeStandingMontage = 0xa38; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BuryCrouchingMontage = 0xa40; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BuryRestCrouchingMontage = 0xa48; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SitOnGroundStandingStartMontage = 0xa50; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SitOnGroundStandingEndMontage = 0xa58; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SitOnGroundCrouchingStartMontage = 0xa60; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SitOnGroundCrouchingEndMontage = 0xa68; // Size: 8, Type: struct UAnimMontage*
			constexpr auto LayOnGroundStandingStartMontage = 0xa70; // Size: 8, Type: struct UAnimMontage*
			constexpr auto LayOnGroundStandingEndMontage = 0xa78; // Size: 8, Type: struct UAnimMontage*
			constexpr auto LayOnGroundCrouchingStartMontage = 0xa80; // Size: 8, Type: struct UAnimMontage*
			constexpr auto LayOnGroundCrouchingEndMontage = 0xa88; // Size: 8, Type: struct UAnimMontage*
			constexpr auto SittingOnGroundAnimation = 0xa90; // Size: 8, Type: struct UAnimSequenceBase*
			constexpr auto LyingOnGroundAnimation = 0xa98; // Size: 8, Type: struct UAnimSequenceBase*
			constexpr auto LightFlareMontage = 0xaa0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto ArmTrapMontage = 0xaa8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto FishingEnterMontage = 0xab0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto FishingLeaveMontage = 0xab8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto FishingCastMontage = 0xac0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto FishingLongCastEndMontage = 0xac8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto FishingShortCastEndMontage = 0xad0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto FishingPullStartMontage = 0xad8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto FishingPullEndMontage = 0xae0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto FishingFishCaughtMontage = 0xae8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto FishingKeepFishMontage = 0xaf0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto FishingDiscardFishMontage = 0xaf8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto FishingWireBreakMontage = 0xb00; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BasicDance1Montage = 0xb08; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BasicDance2Montage = 0xb10; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BasicDance3Montage = 0xb18; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BasicDance4Montage = 0xb20; // Size: 8, Type: struct UAnimMontage*
			constexpr auto BasicDance5Montage = 0xb28; // Size: 8, Type: struct UAnimMontage*
			constexpr auto AdvanceDance1Montage = 0xb30; // Size: 8, Type: struct UAnimMontage*
			constexpr auto AdvanceDance2Montage = 0xb38; // Size: 8, Type: struct UAnimMontage*
			constexpr auto AdvanceDance3Montage = 0xb40; // Size: 8, Type: struct UAnimMontage*
			constexpr auto AdvanceDance4Montage = 0xb48; // Size: 8, Type: struct UAnimMontage*
			constexpr auto AdvanceDance5Montage = 0xb50; // Size: 8, Type: struct UAnimMontage*
			constexpr auto AdvanceDance6Montage = 0xb58; // Size: 8, Type: struct UAnimMontage*
			constexpr auto AdvanceDance7Montage = 0xb60; // Size: 8, Type: struct UAnimMontage*
			constexpr auto InjectSelfMontage = 0xb68; // Size: 8, Type: struct UAnimMontage*
			constexpr auto InjectOtherMontage = 0xb70; // Size: 8, Type: struct UAnimMontage*
			constexpr auto HalloweenGesture1Montage = 0xb78; // Size: 8, Type: struct UAnimMontage*
			constexpr auto HalloweenGesture2Montage = 0xb80; // Size: 8, Type: struct UAnimMontage*
			constexpr auto HalloweenGesture3Montage = 0xb88; // Size: 8, Type: struct UAnimMontage*
			constexpr auto HalloweenGesture4Montage = 0xb90; // Size: 8, Type: struct UAnimMontage*
			constexpr auto RemoveWeedMontage = 0xb98; // Size: 8, Type: struct UAnimMontage*
			constexpr auto RemoveWeedWithHoeMontage = 0xba0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto ApplyPesticideMontage = 0xba8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto AddFertilizerMontage = 0xbb0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto PlantSeedMontage = 0xbb8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto RemovePlantMontage = 0xbc0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto DestroyGardenMontage = 0xbc8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto WashEyesMontage = 0xbd0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto TurnMontageDescription = 0xbd8; // Size: 48, Type: struct FPrisonerTurnMontageDescription
			constexpr auto MinThrowItemSpeed = 0xc08; // Size: 4, Type: float
			constexpr auto MaxThrowItemSpeed = 0xc0c; // Size: 4, Type: float
			constexpr auto MinScreenCenterDotOpacityDecreaseDelay = 0xc10; // Size: 4, Type: float
			constexpr auto MaxScreenCenterDotOpacityDecreaseDelay = 0xc14; // Size: 4, Type: float
			constexpr auto ScreenCenterDotOpacityDecrease = 0xc18; // Size: 4, Type: float
			constexpr auto ScreenCenterDotOpacityIncrease = 0xc1c; // Size: 4, Type: float
			constexpr auto ShortThrowReductionMultiplier = 0xc20; // Size: 4, Type: float
			constexpr auto ThrowingObstacleCheckOffset = 0xc24; // Size: 4, Type: float
			constexpr auto ThrowingObstacleOffset = 0xc28; // Size: 4, Type: float
			constexpr auto ThrowingAnimationSets = 0xc30; // Size: 80, Type: struct TMap<uint8_t , struct FThrowingAnimationSet>
			constexpr auto RespawnTime = 0xc80; // Size: 4, Type: float
			constexpr auto FocusModeZoomEffectCurve = 0xc88; // Size: 8, Type: struct UCurveFloat*
			constexpr auto FocusModeZoomSpeed = 0xc90; // Size: 4, Type: float
			constexpr auto SelfInteractionSegmentInfo = 0xc98; // Size: 16, Type: struct TArray<struct UCircularMenuSegmentInfo*>
			constexpr auto SelfInteractionVoicelineIcons = 0xca8; // Size: 8, Type: struct UCircularMenuSegmentIcons*
			constexpr auto CharacterVoicelines = 0xcb0; // Size: 16, Type: struct TArray<struct UCharacterVoiceline*>
			constexpr auto PrisonWalletComponentClass = 0xcc0; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto MusicPlayerComponentClass = 0xce8; // Size: 8, Type: UPrisonerMusicPlayerComponent*
			constexpr auto WetnessReachableFromSkyChecksInterval = 0xcf0; // Size: 4, Type: float
			constexpr auto DedicatedServerHandleFootstepInterval = 0xcf4; // Size: 4, Type: float
			constexpr auto PlayInstrumentEventNetworkDelay = 0xcf8; // Size: 4, Type: float
			constexpr auto PlayInstrumentExitStateDuration = 0xcfc; // Size: 4, Type: float
			constexpr auto BodyCompositionMorphsComputer = 0xd00; // Size: 8, Type: UPrisonerBodyCompositionMorphsComputer*
			constexpr auto PenisLocationLean = 0xd08; // Size: 12, Type: struct FVector
			constexpr auto PenisLocationFat = 0xd14; // Size: 12, Type: struct FVector
			constexpr auto PenisHandleLocationLean = 0xd20; // Size: 12, Type: struct FVector
			constexpr auto PenisHandleLocationFat = 0xd2c; // Size: 12, Type: struct FVector
			constexpr auto PenisMinSizeHandleZ = 0xd38; // Size: 4, Type: float
			constexpr auto PenisMaxSizeHandleZ = 0xd3c; // Size: 4, Type: float
			constexpr auto PenisGrowOverTimeThreshold = 0xd40; // Size: 4, Type: float
			constexpr auto UnmountSpeedThresholdForRagdoll = 0xd44; // Size: 4, Type: float
			constexpr auto MountTiltAngleForRagdoll = 0xd48; // Size: 4, Type: float
			constexpr auto RareSuicideAnimationChance = 0xd4c; // Size: 4, Type: float
			constexpr auto FaceAgingIntensityCurve = 0xd50; // Size: 8, Type: struct UCurveFloat*
			constexpr auto HairGrowthTotalTime = 0xd58; // Size: 4, Type: float
			constexpr auto FacialHairGrowthTotalTime = 0xd5c; // Size: 4, Type: float
			constexpr auto HairUpdateRate = 0xd60; // Size: 4, Type: float
			constexpr auto ShortHairCurve = 0xd68; // Size: 8, Type: struct UCurveFloat*
			constexpr auto MediumHairCurve = 0xd70; // Size: 8, Type: struct UCurveFloat*
			constexpr auto MediumHairPDOCurve = 0xd78; // Size: 8, Type: struct UCurveFloat*
			constexpr auto MediumHairTopOpacityCurve = 0xd80; // Size: 8, Type: struct UCurveFloat*
			constexpr auto LongHairCurve = 0xd88; // Size: 8, Type: struct UCurveFloat*
			constexpr auto LongHairPDOCurve = 0xd90; // Size: 8, Type: struct UCurveFloat*
			constexpr auto LongHairTopOpacityCurve = 0xd98; // Size: 8, Type: struct UCurveFloat*
			constexpr auto AfroHairCurve = 0xda0; // Size: 8, Type: struct UCurveFloat*
			constexpr auto ShortFacialHairCurve = 0xda8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto MediumFacialHairCurve = 0xdb0; // Size: 8, Type: struct UCurveFloat*
			constexpr auto MediumFacialHairPDOCurve = 0xdb8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto MediumFacialHairTopOpacityCurve = 0xdc0; // Size: 8, Type: struct UCurveFloat*
			constexpr auto LongFacialHairCurve = 0xdc8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto LongFacialHairPDOCurve = 0xdd0; // Size: 8, Type: struct UCurveFloat*
			constexpr auto LongFacialHairTopOpacityCurve = 0xdd8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto MaxRestingAngle = 0xde0; // Size: 4, Type: float
			constexpr auto GenericAcceptanceRadius = 0xde4; // Size: 4, Type: float
			constexpr auto DistanceWhereRotationStarts = 0xde8; // Size: 4, Type: float
			constexpr auto AutoTriggeredVomitingNotification = 0xdf0; // Size: 8, Type: UNotificationDescription*
			constexpr auto AutoTriggeredUrinationNotification = 0xdf8; // Size: 8, Type: UNotificationDescription*
			constexpr auto AutoTriggeredDefecationNotification = 0xe00; // Size: 8, Type: UNotificationDescription*
			constexpr auto UIDataClass = 0xe08; // Size: 8, Type: UPrisonerUIDataImpl*
			constexpr auto DefecateNakedForcedAudioEvent = 0xe10; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto DefecateClothedForcedAudioEvent = 0xe18; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto DefecateNakedForcedDiarrheaAudioEvent = 0xe20; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto DefecateClothedForcedDiarrheaAudioEvent = 0xe28; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto UrinateForcedAudioEvent = 0xe30; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto StartBlowingAirAudioEvent = 0xe38; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto StopBlowingAirAudioEvent = 0xe40; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto PhoenixTearsEffectSound = 0xe48; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto DiarrheaParticleSystem = 0xe50; // Size: 8, Type: struct UParticleSystem*
			constexpr auto FecesClass = 0xe58; // Size: 8, Type: AActor*
			constexpr auto FecesSocketName = 0xe60; // Size: 8, Type: struct FName
			constexpr auto ResponseIdles = 0xe68; // Size: 8, Type: struct FPrisonerCommonData_ResponseIdles
			constexpr auto ParachutingMoveInputNotificationData = 0xe70; // Size: 56, Type: struct FBasicNotificationDescriptionData
			constexpr auto ParachutingChangePoseInputNotificationData = 0xea8; // Size: 56, Type: struct FBasicNotificationDescriptionData
			constexpr auto ParachutingOpenParachuteInputNotificationData = 0xee0; // Size: 56, Type: struct FBasicNotificationDescriptionData
			constexpr auto SkydivingStartAudioEvent = 0xf18; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto SkydivingStopAudioEvent = 0xf20; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto IntroCinematicScreamAudioEvent = 0xf28; // Size: 8, Type: struct UAkAudioEvent*
			constexpr auto MaxSpeedWhileMountedToBeRelevantForHunting = 0xf30; // Size: 4, Type: float
	}
} 
