namespace offsets
{
	namespace UVisionEffectsComponent
	{
			constexpr auto PostProcessPriority = 0xe8; // Size: 4, Type: float
			constexpr auto FadeOutMaterial = 0xf0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto LowLightVisionMaterial = 0xf8; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto NightVisionMaterial = 0x100; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto NightVisionBlendInDuration = 0x108; // Size: 4, Type: float
			constexpr auto NightVisionBlendOutDuration = 0x10c; // Size: 4, Type: float
			constexpr auto AnimalEyesMaterialParameterCollection = 0x110; // Size: 8, Type: struct UMaterialParameterCollection*
			constexpr auto AnimalEyesEmissiveMaterialName = 0x118; // Size: 8, Type: struct FName
			constexpr auto AnimalEyesEmissiveValueWhenNightVisionIsEnabled = 0x120; // Size: 4, Type: float
			constexpr auto FlashbangEffectMaterial = 0x128; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto FallingBlurMaterial = 0x130; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto TakenDamageMaterial = 0x138; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto TakenDamageMaterialParameterCollection = 0x140; // Size: 8, Type: struct UMaterialParameterCollection*
			constexpr auto TakenDamageBlurIntensityParameterName = 0x148; // Size: 8, Type: struct FName
			constexpr auto TakenDamageStainsIntensityParameterName = 0x150; // Size: 8, Type: struct FName
			constexpr auto TakenDamageVignetteIntensityParameterName = 0x158; // Size: 8, Type: struct FName
			constexpr auto TakenDamageBlurShapeCurve = 0x160; // Size: 8, Type: struct UCurveFloat*
			constexpr auto TakenDamageBlurIntensityCurve = 0x168; // Size: 8, Type: struct UCurveFloat*
			constexpr auto TakenDamageBlurDurationCurve = 0x170; // Size: 8, Type: struct UCurveFloat*
			constexpr auto TakenDamageStainsShapeCurve = 0x178; // Size: 8, Type: struct UCurveFloat*
			constexpr auto TakenDamageStainsIntensityCurve = 0x180; // Size: 8, Type: struct UCurveFloat*
			constexpr auto TakenDamageStainsDurationCurve = 0x188; // Size: 8, Type: struct UCurveFloat*
			constexpr auto TakenDamageVignetteShapeCurve = 0x190; // Size: 8, Type: struct UCurveFloat*
			constexpr auto TakenDamageVignetteIntensityCurve = 0x198; // Size: 8, Type: struct UCurveFloat*
			constexpr auto TakenDamageVignetteDurationCurve = 0x1a0; // Size: 8, Type: struct UCurveFloat*
			constexpr auto TakenDamageMaxChromaticAberration = 0x1a8; // Size: 4, Type: float
			constexpr auto TakenDamageCameraShakeClass = 0x1b0; // Size: 8, Type: UMatineeCameraShake*
			constexpr auto TakenDamageCameraShakeScaleCurve = 0x1b8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto TacticsEffectMaterial = 0x1c0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto FocusModeMaterial = 0x1c8; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto DoubleVisionMaterial = 0x1d0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto DoubleVisionIntensityParameterName = 0x1d8; // Size: 8, Type: struct FName
			constexpr auto UnderwaterBlurMaterial = 0x1e0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto PhotoModeTransitionMaterial = 0x1e8; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto ScopeZoomMaterial = 0x1f0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto ScopeZoomBlendPPParameterName = 0x1f8; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomBlackoutDensityParameterName = 0x200; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomChromaticAberrationDampeningParameterName = 0x208; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomCrosshairBaseScaleParameterName = 0x210; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomCrosshairDepthOffsetMultiplierParameterName = 0x218; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomCrosshairScaleMultiplierParameterName = 0x220; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomDistortionPowerParameterName = 0x228; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomDistortionScaleParameterName = 0x230; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomEyeDistanceBlackoutMultiplierParameterName = 0x238; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomGlowIntensityAtNightParameterName = 0x240; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomLensDepthOffsetMultiplierParameterName = 0x248; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomLensScaleParameterName = 0x250; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomLensUIScaleParameterName = 0x258; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomLensZoomParameterName = 0x260; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomOptimalEyeDistanceParameterName = 0x268; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomCrosshairCenterScreenOffsetParameterName = 0x270; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomLensCenterScreenOffsetParameterName = 0x278; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomCrosshairParameterName = 0x280; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomCrosshairColorParameterName = 0x288; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomCrosshairColorAtNightParameterName = 0x290; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomCrosshairGlowColorParameterName = 0x298; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomDirtMaskParameterName = 0x2a0; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomDirtinessParameterName = 0x2a8; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomDarkeningParameterName = 0x2b0; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomLensNormalMapParameterName = 0x2b8; // Size: 8, Type: struct FName
			constexpr auto ScopeZoomLensUIParameterName = 0x2c0; // Size: 8, Type: struct FName
			constexpr auto InjuryMaterial = 0x2c8; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto TraumaMaterial = 0x2d0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto BulletHitMaterial = 0x2d8; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto SickMaterial = 0x2e0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto ColdMaterial = 0x2e8; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto HotMaterial = 0x2f0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto FatigueMaterial = 0x2f8; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto HallucinationMaterial = 0x300; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto EyePressureMaterial = 0x308; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto BloodyEyesMaterial = 0x310; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto RadiationMaterial = 0x318; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto BlackoutMaterial = 0x320; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto BlurredVisionMaterial = 0x328; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto DepthOfFieldMaterial = 0x330; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto PhoenixTearsMaterial = 0x338; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto HeightenedSensesSaturationColor = 0x340; // Size: 16, Type: struct FVector4
			constexpr auto _postProcessSettings = 0x350; // Size: 1376, Type: struct FPostProcessSettings
			constexpr auto _doubleVisionIntensityMaterialInstance = 0xe88; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _headgearOverlayMaterialInstance = 0xe90; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto _scopeZoomMaterialInstance = 0xe98; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _fallingBlurMaterialInstance = 0xea0; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _underwaterPostProcessingCurrent = 0xea8; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto _underwaterPostProcessingLast = 0xeb0; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto _underwaterPostProcessingBlendTime = 0xeb8; // Size: 4, Type: float
			constexpr auto _DOFBlurTime = 0xec4; // Size: 4, Type: float
			constexpr auto _DOFClearBlurTime = 0xec8; // Size: 4, Type: float
			constexpr auto _DOFScopingBlurTime = 0xecc; // Size: 4, Type: float
			constexpr auto _DOFBlurDistanceADS = 0xed0; // Size: 4, Type: float
			constexpr auto _DOFFstopADS = 0xed4; // Size: 4, Type: float
			constexpr auto _injuryMaterial = 0xed8; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _traumaMaterial = 0xee8; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _hallucinationMaterial = 0xef8; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _eyePressureMaterial = 0xf08; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _bloodyEyesMaterial = 0xf18; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _bulletHitMaterial = 0xf28; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _sickMaterial = 0xf38; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _coldMaterial = 0xf48; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _hotMaterial = 0xf58; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _fatigueMaterial = 0xf68; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _radiationMaterial = 0xf78; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _blackoutMaterial = 0xf88; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _blurredVisionMaterial = 0xf98; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _depthOfFieldMaterial = 0xfa8; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto _phoenixTearsMaterial = 0xfb8; // Size: 8, Type: struct UMaterialInstanceDynamic*
	}
} 
