#pragma once 
#include <ABP_Prisoner_WeightLoad_Structs.h>
 
 
 
// AnimBlueprintGeneratedClass ABP_Prisoner_WeightLoad.ABP_Prisoner_WeightLoad_C
// Size: 0xC7C(Inherited: 0x2C0) 
struct UABP_Prisoner_WeightLoad_C : public UPrisonerAnimInstance_WeightLoad
{
	struct FPointerToUberGraphFrame UberGraphFrame;  // 0x2C0(0x8)
	struct FAnimNode_Root AnimGraphNode_Root;  // 0x2C8(0x30)
	struct FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose;  // 0x2F8(0x118)
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;  // 0x410(0x20)
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;  // 0x430(0x20)
	struct FAnimNode_ModifyBone AnimGraphNode_ModifyBone_7;  // 0x450(0x108)
	struct FAnimNode_ModifyBone AnimGraphNode_ModifyBone_6;  // 0x558(0x108)
	struct FAnimNode_ModifyBone AnimGraphNode_ModifyBone_5;  // 0x660(0x108)
	struct FAnimNode_ModifyBone AnimGraphNode_ModifyBone_4;  // 0x768(0x108)
	struct FAnimNode_ModifyBone AnimGraphNode_ModifyBone_3;  // 0x870(0x108)
	struct FAnimNode_CopyBone AnimGraphNode_CopyBone;  // 0x978(0xF0)
	struct FAnimNode_ModifyBone AnimGraphNode_ModifyBone_2;  // 0xA68(0x108)
	struct FAnimNode_ModifyBone AnimGraphNode_ModifyBone;  // 0xB70(0x108)
	float WeightLoadFactor;  // 0xC78(0x4)

	void AnimGraph(struct FPoseLink InPose, struct FPoseLink& AnimGraph); // Function ABP_Prisoner_WeightLoad.ABP_Prisoner_WeightLoad_C.AnimGraph
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_453C5F26411CB286321E8DB6BD390538(); // Function ABP_Prisoner_WeightLoad.ABP_Prisoner_WeightLoad_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_453C5F26411CB286321E8DB6BD390538
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_3BA31DAB4C2251A5551ABF92B5EF6EDC(); // Function ABP_Prisoner_WeightLoad.ABP_Prisoner_WeightLoad_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_3BA31DAB4C2251A5551ABF92B5EF6EDC
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_CopyBone_C78C6C854660251F8AF393A3FFCDAF3D(); // Function ABP_Prisoner_WeightLoad.ABP_Prisoner_WeightLoad_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_CopyBone_C78C6C854660251F8AF393A3FFCDAF3D
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_FD4BD31742A3B9C191645FBFBB26ADB3(); // Function ABP_Prisoner_WeightLoad.ABP_Prisoner_WeightLoad_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_FD4BD31742A3B9C191645FBFBB26ADB3
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_5A9718D344432D8EE2C192ACDBA4E8B6(); // Function ABP_Prisoner_WeightLoad.ABP_Prisoner_WeightLoad_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_5A9718D344432D8EE2C192ACDBA4E8B6
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_D664E21F4D373F17D3BDEF8FEBACC61D(); // Function ABP_Prisoner_WeightLoad.ABP_Prisoner_WeightLoad_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_D664E21F4D373F17D3BDEF8FEBACC61D
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_FED9B57C498EF024308E0B88F1D1CA6A(); // Function ABP_Prisoner_WeightLoad.ABP_Prisoner_WeightLoad_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_FED9B57C498EF024308E0B88F1D1CA6A
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_5988E94F403D4BF88928DA9CC56F17CD(); // Function ABP_Prisoner_WeightLoad.ABP_Prisoner_WeightLoad_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prisoner_WeightLoad_AnimGraphNode_ModifyBone_5988E94F403D4BF88928DA9CC56F17CD
	void ExecuteUbergraph_ABP_Prisoner_WeightLoad(int32_t EntryPoint); // Function ABP_Prisoner_WeightLoad.ABP_Prisoner_WeightLoad_C.ExecuteUbergraph_ABP_Prisoner_WeightLoad
}; 



