#pragma once 
#include <UI_SpawnSectorSelector_Structs.h>
 
 
 
// WidgetBlueprintGeneratedClass UI_SpawnSectorSelector.UI_SpawnSectorSelector_C
// Size: 0x350(Inherited: 0x270) 
struct UUI_SpawnSectorSelector_C : public USpawnSectorSelectorWidget
{
	struct FPointerToUberGraphFrame UberGraphFrame;  // 0x270(0x8)
	struct UButton* Button;  // 0x278(0x8)
	struct UButton* Button_1;  // 0x280(0x8)
	struct UButton* Button_2;  // 0x288(0x8)
	struct UButton* Button_3;  // 0x290(0x8)
	struct UButton* Button_4;  // 0x298(0x8)
	struct UButton* Button_5;  // 0x2A0(0x8)
	struct UButton* Button_6;  // 0x2A8(0x8)
	struct UButton* Button_7;  // 0x2B0(0x8)
	struct UButton* Button_8;  // 0x2B8(0x8)
	struct UButton* Button_9;  // 0x2C0(0x8)
	struct UButton* Button_10;  // 0x2C8(0x8)
	struct UButton* Button_11;  // 0x2D0(0x8)
	struct UButton* Button_12;  // 0x2D8(0x8)
	struct UButton* Button_13;  // 0x2E0(0x8)
	struct UButton* Button_14;  // 0x2E8(0x8)
	struct UButton* Button_15;  // 0x2F0(0x8)
	struct UButton* Button_16;  // 0x2F8(0x8)
	struct UButton* Button_17;  // 0x300(0x8)
	struct UButton* Button_18;  // 0x308(0x8)
	struct UButton* Button_19;  // 0x310(0x8)
	struct UButton* Button_20;  // 0x318(0x8)
	struct UButton* Button_21;  // 0x320(0x8)
	struct UButton* Button_22;  // 0x328(0x8)
	struct UButton* Button_23;  // 0x330(0x8)
	struct UButton* Button_24;  // 0x338(0x8)
	struct UImage* MapImage;  // 0x340(0x8)
	struct UUniformGridPanel* UniformGridPanel_1;  // 0x348(0x8)

	void BndEvt__Button_1_K2Node_ComponentBoundEvent_544_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_1_K2Node_ComponentBoundEvent_544_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_0_K2Node_ComponentBoundEvent_561_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_0_K2Node_ComponentBoundEvent_561_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_2_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_2_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_15_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_15_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_14_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_14_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_13_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_13_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_12_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_12_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_11_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_11_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_10_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_10_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_9_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_9_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_8_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_8_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_7_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_7_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_6_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_6_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_5_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_5_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_4_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_4_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_3_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_3_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_23_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_23_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_22_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_22_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_21_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_21_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_20_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_20_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_19_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_19_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_18_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_18_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_17_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_17_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_16_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_16_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature
	void BndEvt__Button_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature(); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.BndEvt__Button_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature
	void ExecuteUbergraph_UI_SpawnSectorSelector(int32_t EntryPoint); // Function UI_SpawnSectorSelector.UI_SpawnSectorSelector_C.ExecuteUbergraph_UI_SpawnSectorSelector
}; 



